// Package refusal holds the refusal register defined by the human-carried-landing design at HCL-AUDIT-03; shell refusals are recorded by hand, and no test proves that list complete.
package refusal

type Shape string

const (
	Identity Shape = "identity" // The machine establishes that the word is the human's.
	Warning  Shape = "warning"  // The machine prints and records the warning, then complies.
	Question Shape = "question" // The word is stale or names nothing, so the machine asks.
	Agent    Shape = "agent"    // The refusal binds an agent's act only; Override is the human verb past it.
)

type Row struct {
	Code     string // The token exactly as the walk collects it.
	Owner    string // The package or script that emits it.
	Site     string // The file and line of one emitting site.
	Shape    Shape
	Override string // The human verb that carries past it; empty only for Identity and Question.
	Commands int    // Commands between the human's intent and the effect; zero when Override is empty.
	Pending  string // "human-carried-landing" while the Override is not yet in the tree.
}

type Exclusion struct {
	Pattern string // An exact token, or "PREFIX_*" for a prefix.
	Reason  string
}

type Shell struct {
	Script, Line, Prose, Override string
	Record                        bool // true only for a non-overridable record failure.
}

type Defect struct{ Code, Why string }

var Rows = []Row{
	{Code: "LAUNCH_ALREADY_SUPERVISED", Owner: "internal/launch", Site: "launch.go:248", Shape: Question},
	{Code: "LAUNCH_SETTING_INVALID", Owner: "internal/launch", Site: "settings.go:104", Shape: Question},
	{Code: "LAUNCH_BRIEF_OVERSIZE", Owner: "internal/launch", Site: "admit.go:102", Shape: Question},
	{Code: "LAUNCH_BRIEF_PACK_UNFILLED", Owner: "internal/launch", Site: "pack.go:48", Shape: Question},
	{Code: "LAUNCH_BRIEF_PACK_DRIFTED", Owner: "internal/launch", Site: "pack.go:184", Shape: Question},
	{Code: "LAUNCH_BUILD_UNSIZED", Owner: "internal/launch", Site: "admit.go:171", Shape: Question},
	{Code: "LAUNCH_BUILD_OVERSIZE", Owner: "internal/launch", Site: "admit.go:113", Shape: Question},
	{Code: "LAUNCH_READ_UNSIZED", Owner: "internal/launch", Site: "admit.go:51", Shape: Question},
	{Code: "LAUNCH_READ_UNSPLIT", Owner: "internal/launch", Site: "admit.go:139", Shape: Question},
	{Code: "LAUNCH_UNIT_GOAL_BRANCH_REQUIRED", Owner: "internal/launch", Site: "unit_run.go:227", Shape: Question},
	{Code: "RECEIPT_USAGE_INCOMPLETE", Owner: "internal/receipt", Site: "receipt.go:399", Shape: Question},
	{Code: "UNIT_PLAN_INVALID", Owner: "internal/launch", Site: "unit_plan.go:227", Shape: Question},
	{Code: "UNIT_RUN_BUSY", Owner: "internal/launch", Site: "unit_run.go:872", Shape: Question},
	{Code: "UNIT_RUN_NOT_AWAITING", Owner: "internal/launch", Site: "unit_run.go:806", Shape: Question},
	{Code: "UNIT_FOLLOW_UP_MISSING", Owner: "internal/launch", Site: "unit_run.go:810", Shape: Question},
	{Code: "BATCH_CHAIN_CONFLICT", Owner: "internal/landing/batch", Site: "chain.go:111", Shape: Question},
	{Code: "BATCH_CLOSED", Owner: "internal/landing/batch", Site: "join.go:36", Shape: Question},
	{Code: "BATCH_GOAL_ELSEWHERE", Owner: "internal/landing/batch", Site: "join.go:308", Shape: Question},
	{Code: "BATCH_JOIN_CONFLICT", Owner: "internal/landing/batch", Site: "join.go:94", Shape: Question},
	{Code: "BATCH_JOIN_REREAD", Owner: "internal/landing/batch", Site: "join.go:245", Shape: Question},
	{Code: "BATCH_JOIN_UNREAD", Owner: "internal/landing/batch", Site: "branch.go:106", Shape: Question},
	{Code: "BATCH_JOIN_GATE_RED", Owner: "internal/landing/batch", Site: "gate.go:63", Shape: Question},
	{Code: "BATCH_JOIN_TEST_DROPPED", Owner: "internal/landing/batch", Site: "gate.go:201", Shape: Question},
	{Code: "BATCH_JOIN_CHAIN_NOT_IMPLEMENTATION", Owner: "internal/landing/batch", Site: "chain.go:48", Shape: Question},
	{Code: "BATCH_JOIN_CHAIN_REQUIRED", Owner: "internal/landing/batch", Site: "chain.go:42", Shape: Question},
	{Code: "BATCH_JOIN_CHAIN_REVISION_MOVED", Owner: "internal/landing/batch", Site: "chain.go:61", Shape: Question},
	{Code: "BATCH_JOIN_CHAIN_UNCLOSED", Owner: "internal/landing/batch", Site: "chain.go:51", Shape: Question},
	{Code: "BATCH_JOIN_CHAIN_UNREAD", Owner: "internal/landing/batch", Site: "chain.go:45", Shape: Question},
	{Code: "BATCH_SEALED", Owner: "internal/landing/batch", Site: "join.go:39", Shape: Question},
	{Code: "BATCH_SEAL_CHANGED_DURING_GATE", Owner: "internal/landing/batch", Site: "seal.go:66", Shape: Question},
	{Code: "BATCH_SEAL_GATE_RED", Owner: "internal/landing/batch", Site: "seal.go:201", Shape: Question},
	{Code: "BATCH_UNIT_ELSEWHERE", Owner: "internal/landing/batch", Site: "join.go:313", Shape: Question},
	{Code: "BATCH_JOIN_AUTHOR_UNBOUND", Owner: "cmd/metasystem", Site: "landing_batch_join.go:114", Shape: Question},
	{Code: "BATCH_JOIN_BASE_MOVED", Owner: "cmd/metasystem", Site: "landing_batch_join.go:233", Shape: Question},
	{Code: "BATCH_JOIN_REVISION_MOVED", Owner: "cmd/metasystem", Site: "landing_batch_join.go:206", Shape: Question},
	{Code: "BATCH_BASE_MOVED", Owner: "cmd/metasystem", Site: "landing_batch_prove.go:274", Shape: Question},
	{Code: "BATCH_MEMBER_BUDGET_REFUSED", Owner: "cmd/metasystem", Site: "proof_run.go:887", Shape: Question},
	{Code: "BATCH_OWNER_IDENTITY_UNKNOWN", Owner: "cmd/metasystem", Site: "landing_batch_owner.go:158", Shape: Question},
	{Code: "BATCH_OWNER_INDETERMINATE", Owner: "cmd/metasystem", Site: "landing_batch_owner.go:134", Shape: Question},
	{Code: "BATCH_OWNER_OWNED_ELSEWHERE", Owner: "cmd/metasystem", Site: "landing_batch_owner.go:168", Shape: Question},
	{Code: "CADENCE_OWNER_UNCONFIGURED", Owner: "cmd/metasystem", Site: "gate_cadence.go:103", Shape: Question},
	{Code: "CADENCE_NOT_LANDING_OWNER", Owner: "cmd/metasystem", Site: "gate_cadence.go:61", Shape: Question},
	{Code: "CADENCE_FETCH_REFUSED", Owner: "cmd/metasystem", Site: "gate_cadence.go:157", Shape: Question},
	{Code: "CADENCE_LEDGER_UNREADABLE", Owner: "cmd/metasystem", Site: "gate_cadence.go:163", Shape: Question},
	{Code: "BATCH_PROOF_INPUT_MOVED", Owner: "internal/landing/batch", Site: "prove.go:56", Shape: Question},
	{Code: "BATCH_PROOF_NOT_ADMITTED", Owner: "internal/landing/batch", Site: "prove.go:93", Shape: Question},
	{Code: "BATCH_PROOF_STATE_REFUSED", Owner: "internal/landing/batch", Site: "prove.go:44", Shape: Question},
	{Code: "BATCH_PROOF_UNION_UNCOVERED", Owner: "internal/landing/batch", Site: "prove.go:51", Shape: Question},
	{Code: "BATCH_REOPEN_SAME_TREE", Owner: "internal/landing/batch", Site: "reopen.go:32", Shape: Question},
	{Code: "BATCH_LANDING_BRANCH_MOVED", Owner: "internal/landing/batch", Site: "transport.go:64", Shape: Question},
	{Code: "BATCH_LANDING_BRANCH_PREP_REFUSED", Owner: "internal/landing/batch", Site: "transport.go:53", Shape: Question},
	{Code: "BATCH_LAND_AUTHOR_UNBOUND", Owner: "internal/landing/batch", Site: "transport.go:276", Shape: Question},
	{Code: "BATCH_LAND_CLEANUP_REFUSED", Owner: "internal/landing/batch", Site: "transport.go:230", Shape: Question},
	{Code: "BATCH_LAND_COMMIT_REFUSED", Owner: "internal/landing/batch", Site: "land.go:402", Shape: Question},
	{Code: "BATCH_LAND_DELEGATION_REFUSED", Owner: "internal/landing/batch", Site: "land.go:116", Shape: Question},
	{Code: "BATCH_LAND_HELD_REFUSED", Owner: "internal/landing/batch", Site: "land.go:445", Shape: Question},
	{Code: "BATCH_LAND_PUSH_REFUSED", Owner: "internal/landing/batch", Site: "transport.go:166", Shape: Question},
	{Code: "BATCH_LAND_RECEIPT_REFUSED", Owner: "internal/landing/batch", Site: "land.go:381", Shape: Question},
	{Code: "BATCH_LAND_STATE_REFUSED", Owner: "internal/landing/batch", Site: "land.go:104", Shape: Question},
	{Code: "BATCH_LAND_TRUNK_MOVED", Owner: "cmd/metasystem", Site: "landing_batch_land.go:538", Shape: Question},
	{Code: "BATCH_LAND_UNPROVENANCED", Owner: "internal/landing/batch", Site: "transport.go:307", Shape: Question},
	{Code: "BATCH_LAND_UNWIRED", Owner: "internal/landing/batch", Site: "land.go:180", Shape: Question},
	{Code: "BATCH_P6_REFUSED", Owner: "internal/landing/batch", Site: "recovery.go:43", Shape: Question},
	{Code: "BATCH_RECOVERY_NOT_PUSHED", Owner: "internal/landing/batch", Site: "recovery.go:32", Shape: Question},
	{Code: "BATCH_WAIT_BOUND", Owner: "internal/landing/batch", Site: "wait.go:24", Shape: Question},
	{Code: "BATCH_WITHDRAW_REFUSED", Owner: "internal/landing/batch", Site: "withdraw.go:41", Shape: Question},
	{Code: "GOAL_REVISION_MOVED", Owner: "cmd/metasystem", Site: "proof_run.go:616", Shape: Question},
	{Code: "CANDIDATE_GOAL_MOVED", Owner: "cmd/metasystem", Site: "proof_run.go:417", Shape: Question},
	{Code: "CANDIDATE_GOAL_REFUSED", Owner: "cmd/metasystem", Site: "proof_run.go:460", Shape: Question},
	{Code: "PROOF_AUTHORITY_REQUIRED", Owner: "cmd/metasystem", Site: "proof_run.go:502", Shape: Question},
	{Code: "PROOF_AUTHORITY_ARC_MATE_REFUSED", Owner: "cmd/metasystem", Site: "proof_run.go:578", Shape: Question},
	{Code: "GOAL_DONE_READ_ITEMS_OPEN", Owner: "internal/goal", Site: "readitems.go:291", Shape: Question},
	{Code: "TRUNK_RED_OWNER_UNBOUND", Owner: "internal/landing/batch", Site: "trunkred.go:70", Shape: Question},
	{Code: "TRUNK_RED_RECORD_PENDING", Owner: "internal/landing/batch", Site: "trunkred_record.go:11", Shape: Question},
	{Code: "TRUNK_RED_RECORD_FAILED", Owner: "internal/landing/batch", Site: "trunkred_record.go:37", Shape: Question},
	{Code: "TRUNK_RED_UNKNOWN", Owner: "internal/goal", Site: "trunkred.go:553", Shape: Question},
	{Code: "TRUNK_RED_CLOSED", Owner: "internal/goal", Site: "trunkred.go:559", Shape: Question},
	{Code: "TRUNK_RED_CHANGED", Owner: "internal/goal", Site: "trunkred.go:564", Shape: Question},
	{Code: "TRUNK_RED_FIX_GOAL_UNKNOWN", Owner: "internal/goal", Site: "trunkred.go:618", Shape: Question},
	{Code: "TRUNK_RED_OWNED_ELSEWHERE", Owner: "internal/goal", Site: "trunkred.go:622", Shape: Agent, Override: "goal trunk-red own --by", Commands: 1},
	{Code: "TRUNK_RED_CLOSE_IS_HUMAN", Owner: "internal/goal", Site: "trunkred.go:655", Shape: Agent, Override: "goal trunk-red close --by --why", Commands: 1},
	{Code: "AGENT_IN_AUTHORITY_CHAIN", Owner: "internal/humanauthority", Site: "authority.go:745", Shape: Identity},
	{Code: "ANCESTRY_CHANGED", Owner: "internal/humanauthority", Site: "authority.go:507", Shape: Identity},
	{Code: "ANCESTRY_CYCLE", Owner: "internal/humanauthority", Site: "authority.go:701", Shape: Identity},
	{Code: "ANCESTRY_UNREADABLE", Owner: "internal/humanauthority", Site: "authority.go:478", Shape: Identity},
	{Code: "ARGV_UNREADABLE", Owner: "internal/humanauthority", Site: "authority.go:489", Shape: Identity},
	{Code: "PROCESS_REUSED", Owner: "internal/humanauthority", Site: "authority.go:501", Shape: Identity},
	{Code: "TERMINAL_NOT_ENROLLED", Owner: "internal/humanauthority", Site: "authority.go:823", Shape: Identity},
	{Code: "TERMINAL_NOT_REACHED", Owner: "internal/humanauthority", Site: "authority.go:648", Shape: Identity},

	{Code: "BRAIN_REFUSED", Owner: "cmd/metasystem", Site: "delegate.go:50", Shape: Agent, Override: "brain withdraw", Commands: 1},
	{Code: "CONTEXT_EVIDENCE_RETIRED", Owner: "internal/steward", Site: "contextreport.go:62", Shape: Question},
	{Code: "HANDOFF_HUMAN_UNPROVEN", Owner: "internal/steward", Site: "handoff_capture.go:1186", Shape: Identity},
	{Code: "HANDOFF_DELEGATES_UNDECLARED", Owner: "cmd/metasystem", Site: "context_verbs.go:392", Shape: Question},
	{Code: "HANDOFF_DELEGATE_INCOMPLETE", Owner: "cmd/metasystem", Site: "context_verbs.go:427", Shape: Question},
	{Code: "HANDOFF_DELEGATE_OUTPUT_MISMATCH", Owner: "cmd/metasystem", Site: "context_verbs.go:409", Shape: Question},
	{Code: "HANDOFF_DELEGATE_UNDECLARED", Owner: "cmd/metasystem", Site: "context_verbs.go:435", Shape: Question},
	{Code: "HANDOFF_DELEGATE_UNKNOWN", Owner: "cmd/metasystem", Site: "context_verbs.go:406", Shape: Question},
	{Code: "HANDOFF_LAUNCH_IN_FLIGHT", Owner: "internal/steward", Site: "handoff_capture.go:502", Shape: Question},
	{Code: "HANDOFF_NOTE_LACKS_OUTPUT", Owner: "internal/steward", Site: "handoff_capture.go:695", Shape: Question},
	{Code: "HANDOFF_NOTE_MISSING", Owner: "internal/steward", Site: "handoff_capture.go:665", Shape: Question},
	{Code: "HANDOFF_NOTE_OUTSIDE_MEMORY", Owner: "internal/steward", Site: "handoff_capture.go:669", Shape: Question},
	{Code: "HANDOFF_NOTE_STALE", Owner: "internal/steward", Site: "handoff_capture.go:706", Shape: Question},
	{Code: "HANDOFF_NOT_FOUND", Owner: "internal/steward", Site: "handoff_capture.go:1338", Shape: Question},
	{Code: "HANDOFF_NOT_HOLDER", Owner: "internal/steward", Site: "handoff_capture.go:299", Shape: Question},
	{Code: "HANDOFF_NOT_LIVE", Owner: "internal/steward", Site: "handoff_capture.go:1257", Shape: Question},
	{Code: "HANDOFF_NO_GOAL", Owner: "internal/steward", Site: "handoff_capture.go:384", Shape: Question},
	{Code: "HANDOFF_OTHER_SESSION", Owner: "internal/steward", Site: "handoff_capture.go:1207", Shape: Agent, Override: "metasystem context handoff --root <installation> --cancel <nonce> --by <human>, typed at an enrolled or agent-free terminal", Commands: 1},
	{Code: "HANDOFF_OTHER_PENDING", Owner: "internal/steward", Site: "handoff_capture.go:1080", Shape: Question},
	{Code: "HANDOFF_REFERENCE", Owner: "internal/steward", Site: "handoff_capture.go:243", Shape: Question},
	{Code: "HANDOFF_STATE_MISMATCH", Owner: "internal/steward", Site: "handoff_capture.go:1370", Shape: Question},
	{Code: "HANDOFF_STATE_TOO_LARGE", Owner: "internal/steward", Site: "handoff_capture.go:903", Shape: Question},
	{Code: "HANDOFF_TASKS_IN_FLIGHT", Owner: "cmd/metasystem", Site: "context_verbs.go:387", Shape: Question},
	{Code: "HANDOFF_UNOBSERVABLE", Owner: "internal/steward", Site: "handoff_capture.go:328", Shape: Question},
	{Code: "HANDOFF_WAIT_IN_FLIGHT", Owner: "internal/steward", Site: "handoff_capture.go:442", Shape: Question},
	{Code: "HANDOFF_WAIT_UNENDABLE", Owner: "internal/steward", Site: "handoff_waits.go:142", Shape: Question},

	{Code: "APPROVAL_REQUIRED", Owner: "internal/goal", Site: "approval.go:267", Shape: Agent, Override: "goal approve", Commands: 1},
	{Code: "APPROVAL_EXPIRED", Owner: "internal/goal", Site: "approval.go:375", Shape: Agent, Override: "goal approve", Commands: 1},
	{Code: "RELAY_AFTER_ENROLLMENT", Owner: "internal/goal", Site: "approval.go:426", Shape: Identity},
	{Code: "GOAL_NORM_REFUSED", Owner: "internal/goal", Site: "norm.go:101", Shape: Agent, Override: "goal set-budget then --approved-ref", Commands: 2},
	{Code: "GOAL_BRANCH_RANGE", Owner: "internal/goal/branch", Site: "range.go:51", Shape: Question},
	{Code: "GOAL_BRANCH_ENDPOINT_UNSUPPORTED", Owner: "cmd/metasystem", Site: "goal_branch.go:561", Shape: Question},
	{Code: "GOAL_BRANCH_UNAVAILABLE", Owner: "internal/goal/branch", Site: "commit.go:73", Shape: Question},
	{Code: "GOAL_BRANCH_NOT_HOLDER", Owner: "internal/goal/branch", Site: "commit.go:61", Shape: Question},
	{Code: "GOAL_BRANCH_CHECKOUT_ARMED", Owner: "internal/goal/branch", Site: "commit.go:96", Shape: Question},
	{Code: "GOAL_BRANCH_LEASE_MOVED", Owner: "internal/goal/branch", Site: "push.go:321", Shape: Question},
	{Code: "GOAL_BRANCH_CLAIM_LOST", Owner: "internal/goal/branch", Site: "push.go:288", Shape: Question},
	{Code: "GOAL_BRANCH_PUSH_UNKNOWN", Owner: "internal/goal/branch", Site: "push.go:295", Shape: Question},
	{Code: "GOAL_BRANCH_STALE", Owner: "internal/goal/branch", Site: "push.go:202", Shape: Question},
	{Code: "GOAL_PARK_UNPUSHED", Owner: "internal/goal/branch", Site: "status.go:99", Shape: Question},
	{Code: "GOAL_LAND_PARTIAL", Owner: "internal/goal/branch", Site: "land.go:600", Shape: Question},
	{Code: "GOAL_UNIT_REREAD", Owner: "internal/goal/branch", Site: "land.go:260", Shape: Question},
	{Code: "GOAL_LAND_UNPROVEN", Owner: "internal/goal/branch", Site: "land.go:430", Shape: Question},
	{Code: "GOAL_LAND_RETRY", Owner: "internal/goal/branch", Site: "land.go:757", Shape: Question},
	{Code: "GOAL_LAND_UNCHECKED", Owner: "internal/goal/branch", Site: "land.go:763", Shape: Question},
	{Code: "GOAL_LAND_BRANCH_MOVED", Owner: "internal/goal/branch", Site: "land.go:779", Shape: Question},
	{Code: "GOAL_LAND_TRUNK_MOVED", Owner: "internal/goal/branch", Site: "publish.go:86", Shape: Question},
	{Code: "GOAL_LAND_VERIFY", Owner: "internal/goal/branch", Site: "verify.go:46", Shape: Question},
	{Code: "GOAL_LAND_AUTHOR_UNBOUND", Owner: "internal/goal/branch", Site: "land.go:210", Shape: Question},
	{Code: "GOAL_LAND_TRUNK_RED", Owner: "internal/goal/branch", Site: "red.go:215", Shape: Question},
	{Code: "GOAL_SWEEP_UNLANDED", Owner: "internal/goal/branch", Site: "sweep.go:227", Shape: Question},
	{Code: "GOAL_READ_UNGATED", Owner: "internal/goal/branch", Site: "attest.go:408", Shape: Question},
	{Code: "GOAL_READ_TESTS_UNNAMED", Owner: "internal/goal/branch", Site: "attest.go:208", Shape: Question},
	{Code: "GOAL_READ_STALE", Owner: "internal/goal/branch", Site: "attest.go:420", Shape: Question},
	{Code: "GOAL_READ_INVALID", Owner: "internal/goal/branch", Site: "attest.go:160", Shape: Question},
	{Code: "attested-malformed-id", Owner: "internal/landing", Site: "attested.go:30", Shape: Question},
	{Code: "attested-unreadable", Owner: "internal/landing", Site: "attested.go:17", Shape: Question},
	{Code: "attested-invalid", Owner: "internal/landing", Site: "attested.go:24", Shape: Question},
	{Code: "attested-not-critic", Owner: "internal/landing", Site: "attested.go:50", Shape: Question},
	{Code: "attested-goal-mismatch", Owner: "internal/landing", Site: "attested.go:19", Shape: Question},
	{Code: "attested-change-mismatch", Owner: "internal/landing", Site: "attested.go:21", Shape: Question},
	{Code: "attested-not-design-bearing", Owner: "internal/landing", Site: "attested.go:53", Shape: Question},
	{Code: "GOAL_SPLIT_REFUSED", Owner: "internal/goal", Site: "split.go:243", Shape: Agent},
	{Code: "GOAL_CLAIM_QUOTA", Owner: "internal/goal", Site: "verbs.go:1008", Shape: Question},
	{Code: "REBIND_EPOCH_UNAUTHENTICATED", Owner: "internal/goal", Site: "verbs.go:252", Shape: Identity},
	{Code: "SET_BUDGET_FENCED_SAME_TUPLE", Owner: "internal/goal", Site: "verbs.go:1367", Shape: Question},
	{Code: "SPLIT_RATIFY_REFUSED", Owner: "internal/goal", Site: "split.go:386", Shape: Question},
	{Code: "SWEEP_DUPLICATE_GOAL", Owner: "internal/goal", Site: "approval.go:86", Shape: Question},
	{Code: "SWEEP_INCOMPLETE", Owner: "internal/goal", Site: "approval.go:109", Shape: Question},
	{Code: "SWEEP_LISTING_CHANGED", Owner: "internal/goal", Site: "approval.go:170", Shape: Question},
	{Code: "SWEEP_MALFORMED_ROW", Owner: "internal/goal", Site: "approval.go:46", Shape: Question},
	{Code: "SWEEP_UNKNOWN_GOAL", Owner: "internal/goal", Site: "approval.go:90", Shape: Question},
	{Code: "ELAPSED_LIMIT", Owner: "internal/dispatch", Site: "stop.go:102", Shape: Agent, Override: "goal resume", Commands: 1},
	{Code: "CORRUPT_OVER_LIMIT", Owner: "internal/dispatch", Site: "stop.go:105", Shape: Agent, Override: "goal resume", Commands: 1},

	{Code: "BUDGET_UNKNOWN", Owner: "internal/dispatch", Site: "admission.go:104", Shape: Agent, Override: "goal set-budget", Commands: 1},
	{Code: "BUDGET_REFUSED", Owner: "internal/dispatch", Site: "admission.go:548", Shape: Agent, Override: "goal set-budget", Commands: 1},
	{Code: "CANDIDATE_EXTENSION_REFUSED", Owner: "internal/dispatch", Site: "admission.go:396", Shape: Question},
	{Code: "HAZARD_REFUSED", Owner: "internal/dispatch", Site: "admission.go:275", Shape: Agent, Override: "goal edit --tier 2 --why", Commands: 3},
	{Code: "RISK_UNANSWERED", Owner: "internal/dispatch", Site: "admission.go:271", Shape: Agent, Override: "goal classify-sweep or goal unapprove, goal edit --risk, goal approve", Commands: 3},
	{Code: "CLOCK_REGRESSED", Owner: "internal/dispatch", Site: "budget.go:340", Shape: Agent, Override: "goal set-budget", Commands: 1},
	{Code: "ADMISSION_CLOSED_ELAPSED", Owner: "internal/dispatch", Site: "budget.go:857", Shape: Agent, Override: "goal resume", Commands: 1},
	{Code: "ELAPSED_BREACH", Owner: "internal/steward", Site: "health.go:1314", Shape: Agent, Override: "goal resume", Commands: 1},
	{Code: "BRIEF_AUTHORITY_REFUSED", Owner: "internal/dispatch", Site: "brief.go:38", Shape: Question},
	{Code: "BRIEF_BOUNDS_INVALID", Owner: "internal/dispatch", Site: "brief.go:57", Shape: Question},
	{Code: "BRIEF_BOUNDS_UNREADABLE", Owner: "internal/validate", Site: "brief_bounds_source.go:19", Shape: Question},
	{Code: "OBLIGATION_REFUSED", Owner: "internal/dispatch", Site: "governed.go:138", Shape: Agent, Override: "goal set-obligation", Commands: 1},
	{Code: "SLICE_CAP_REFUSED", Owner: "internal/dispatch", Site: "slice.go:63", Shape: Agent, Override: "goal approve or goal set-budget, then --approved-ref", Commands: 2},
	{Code: "SLICE_START_UNRECORDED", Owner: "internal/dispatch", Site: "claim.go:386", Shape: Agent, Override: "goal recover", Commands: 1},
	{Code: "slice-approval-refused", Owner: "internal/dispatch", Site: "claim.go:271", Shape: Agent, Override: "goal approve", Commands: 1},
	{Code: "REFERENCE_MISMATCH", Owner: "internal/dispatch", Site: "references.go:19", Shape: Agent, Override: "delegate (a fresh composition)", Commands: 1},
	{Code: "SUBJECT_MISMATCH", Owner: "internal/dispatch", Site: "read_subject_compute.go:244", Shape: Agent, Override: "dispatch.sh follow-up on the implementer, validate conformance --stage review --job <that round>, dispatch the critic again", Commands: 3},
	{Code: "CONCURRENT_READ", Owner: "internal/dispatch", Site: "read_admission.go:202", Shape: Agent, Override: "dispatch.sh cancel --job <outstanding critic round>, then dispatch the critic again", Commands: 2},
	{Code: "REDUNDANT_READ", Owner: "internal/dispatch", Site: "read_admission.go:223", Shape: Agent, Override: "dispatch.sh close --job <prior critic root>", Commands: 1},
	{Code: "DELEGATE_RECEIPT_REFUSED", Owner: "internal/validate", Site: "conformance.go:720", Shape: Agent, Override: "remove the delegate change to memory/receipts.log, then validate conformance --stage review --job <that round>", Commands: 2},
	{Code: "TEST_POLICY_ENGINE_REQUIRED", Owner: "internal/enginecause", Site: "cause.go:252", Shape: Agent, Override: "the run: command of the line's cause (internal/enginecause.Table)", Commands: 9},
	{Code: "PARALLEL_RATCHET_REFUSED", Owner: "cmd/metasystem", Site: "audit.go:176", Shape: Question},
	{Code: "TEST_CONTRACT_REQUIRED", Owner: "internal/testpolicy", Site: "contract.go:216", Shape: Question},
	{Code: "TEST_CONTRACT_INVALID", Owner: "cmd/metasystem", Site: "runtime_setup.go:63", Shape: Question},
	{Code: "TEST_GROUP_SELECTION_REFUSED", Owner: "internal/testpolicy", Site: "select.go:109", Shape: Question},
	{Code: "RETRY_PRIOR_OUTSIDE_TREE", Owner: "internal/proofrun", Site: "attempt.go:1042", Shape: Question},
	{Code: "ADMISSION_OVERLAP_UNKNOWN", Owner: "internal/proofrun", Site: "admission.go:74", Shape: Question},
	{Code: "ADMISSION_NESTING_UNKNOWN", Owner: "internal/proofrun", Site: "admission.go:78", Shape: Question},
	{Code: "TEST_POLICY_COVERAGE_FLOOR_LOWERED", Owner: "cmd/metasystem", Site: "test.go:556", Shape: Question},
	{Code: "TESTING_MERGE_CONFLICT", Owner: "internal/testpolicy/contractmerge", Site: "merge.go:36", Shape: Question},
	{Code: "TESTING_CONTRACT_INVALID", Owner: "internal/testpolicy/contractmerge", Site: "merge.go:40", Shape: Question},
	{Code: "TESTING_ADD_TESTS_REFUSED", Owner: "internal/testpolicy/contractmerge", Site: "addtests.go:72", Shape: Question},
	{Code: "TESTING_MERGE_DRIVER_UNRESOLVED", Owner: "internal/testpolicy/contractgit", Site: "driver.go:59", Shape: Agent, Override: "run the verb from an installed metasystem binary", Commands: 1},
	{Code: "TESTING_MERGE_ATTRIBUTE_MISUSE", Owner: "internal/testpolicy/contractgit", Site: "transition.go:219", Shape: Question},
	{Code: "TESTING_CONTRACT_HAND_MERGED", Owner: "internal/testpolicy/contractgit", Site: "transition.go:128", Shape: Question},

	{Code: "advance-checkout-locked", Owner: "internal/landing", Site: "advance.go:41", Shape: Agent, Override: "wait, then fetch, advance, push", Commands: 3},
	{Code: "advance-not-on-branch", Owner: "internal/landing", Site: "advance.go:51", Shape: Agent, Override: "git switch <branch>; fetch, advance, push", Commands: 4},
	{Code: "advance-index-not-empty", Owner: "internal/landing", Site: "advance.go:69", Shape: Agent, Override: "land or unstage the staged paths; fetch, advance, push", Commands: 4},
	{Code: "advance-rebase-conflict", Owner: "internal/landing", Site: "advance.go:95", Shape: Agent, Override: "carry dirty registers first, then git rebase in the real checkout and resolve; push", Commands: 4},
	{Code: "advance-unstaged-drift", Owner: "internal/landing", Site: "advance.go:185", Shape: Agent, Override: "land or restore the named path; fetch, advance, push", Commands: 4},
	{Code: "advance-register-removed", Owner: "internal/landing", Site: "advance.go:180", Shape: Agent, Override: "restore the register from the upstream by hand; fetch, advance, push", Commands: 4},
	{Code: "advance-register-contended", Owner: "internal/landing", Site: "advance.go:190", Shape: Agent, Override: "land.sh --direct-fix register-carriage <registers>", Commands: 1},
	{Code: "advance-head-moved", Owner: "internal/landing", Site: "advance.go:209", Shape: Agent, Override: "read git reflog <branch>; fetch, advance, push", Commands: 4},

	{Code: "malformed-candidate-tree", Owner: "internal/landing", Site: "observe.go:120", Shape: Question},
	{Code: "candidate-tree-unreadable", Owner: "internal/landing", Site: "observe.go:124", Shape: Question},
	{Code: "evaluator-unavailable", Owner: "scripts/agents", Site: "commit.sh:627", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "missing-declaration", Owner: "internal/landing", Site: "observe.go:136", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "conflicting-declarations", Owner: "internal/landing", Site: "observe.go:127", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "path-unclassified", Owner: "internal/landing", Site: "observe.go:1093", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "ledger-path-not-goal-verb", Owner: "internal/landing", Site: "observe.go:1077", Shape: Agent, Override: "the owning goal verb", Commands: 1},
	{Code: "runtime-path-refused", Owner: "internal/landing", Site: "observe.go:1082", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "exact-revert-record-refused", Owner: "internal/landing", Site: "observe.go:1611", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "goal-item-not-held", Owner: "internal/landing", Site: "observe.go:1108", Shape: Agent, Override: "goal steal", Commands: 1},
	{Code: "goal-binding-missing", Owner: "internal/landing", Site: "observe.go:370", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "goal-binding-mismatch", Owner: "internal/landing", Site: "observe.go:374", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "goal-revision-moved", Owner: "internal/landing", Site: "observe.go:1116", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "goal-revision-unbound", Owner: "internal/landing", Site: "held.go:178", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "machine-trailer-malformed", Owner: "internal/landing", Site: "held.go:91", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "endpoint-mismatch", Owner: "internal/landing", Site: "held.go:125", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "range-not-linear", Owner: "internal/landing", Site: "held.go:242", Shape: Agent, Override: "rebase onto the fetched tip, or land through land.sh", Commands: 1},
	{Code: "record-not-owned", Owner: "internal/landing", Site: "observe.go:310", Shape: Agent, Override: "goal claim of the owning goal", Commands: 1},
	{Code: "malformed-chain-id", Owner: "internal/landing", Site: "observe.go:349", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-record-unreadable", Owner: "internal/landing", Site: "observe.go:355", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-record-malformed", Owner: "internal/landing", Site: "observe.go:359", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-not-implementation", Owner: "internal/landing", Site: "observe.go:380", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-not-design-bearing", Owner: "internal/landing", Site: "observe.go:408", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-open", Owner: "internal/landing", Site: "observe.go:411", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-output-unreadable", Owner: "internal/landing", Site: "observe.go:474", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-output-mismatch", Owner: "internal/landing", Site: "observe.go:480", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-has-uncarried-paths", Owner: "internal/landing", Site: "observe.go:533", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-base-unproven", Owner: "internal/validate", Site: "recertification.go:762", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-source-changed", Owner: "internal/validate", Site: "recertification.go:733", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-overlap", Owner: "internal/validate", Site: "recertification.go:785", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-unproven", Owner: "internal/validate", Site: "recertification.go:744", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-worktree-incomplete", Owner: "internal/validate", Site: "recertification.go:919", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-timeout", Owner: "internal/validate", Site: "recertification.go:596", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-target-moved", Owner: "internal/landing", Site: "observe.go:111", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-test-command-refused", Owner: "internal/landing", Site: "observe.go:144", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-recertification-park-failed", Owner: "internal/landing", Site: "park.go:76", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "register-carriage-policy-unreadable", Owner: "internal/landing", Site: "observe.go:171", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "register-carriage-path-refused", Owner: "internal/landing", Site: "observe.go:1098", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "register-carriage-not-append-only", Owner: "internal/landing", Site: "observe.go:239", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "malformed-revert-commit", Owner: "internal/landing", Site: "observe.go:1431", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "direct-fix-policy-unreadable", Owner: "internal/landing", Site: "observe.go:1437", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "not-exact-revert", Owner: "internal/landing", Site: "observe.go:1500", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "direct-fix-floor-refused", Owner: "internal/landing", Site: "observe.go:1068", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "unknown-direct-fix-class", Owner: "internal/landing", Site: "observe.go:1469", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-full-gate-refused", Owner: "internal/landing", Site: "observe.go:403", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "chain-test-receipt-refused", Owner: "internal/landing", Site: "observe.go:393", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "proof-input-moved-after-receipt", Owner: "cmd/metasystem", Site: "test.go:1381", Shape: Agent, Override: "reset to the pushed tip, re-stage, landing test-receipt --mode auto, land again", Commands: 4},
	{Code: "tier1-declaration-refused", Owner: "internal/landing", Site: "tierone.go:35", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "tier1-policy-unreadable", Owner: "internal/landing", Site: "tierone.go:62", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "tier1-root-refused", Owner: "internal/landing", Site: "tierone.go:39", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "tier1-floor-refused", Owner: "internal/landing", Site: "tierone.go:95", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "tier1-diff-shape-refused", Owner: "internal/landing", Site: "tierone.go:115", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "tier1-file-bound-refused", Owner: "internal/landing", Site: "tierone.go:118", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "tier1-line-bound-refused", Owner: "internal/landing", Site: "tierone.go:121", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "tier1-receipt-refused", Owner: "internal/landing", Site: "tierone.go:125", Shape: Agent, Override: "land.sh --carried", Commands: 1},
	{Code: "tier1-full-gate-refused", Owner: "internal/landing", Site: "tierone.go:131", Shape: Agent, Override: "land.sh --carried", Commands: 1},

	{Code: "carry-ledger-moved", Owner: "internal/landing", Site: "carried.go:44", Shape: Question},
	{Code: "carry-remote-required", Owner: "internal/goal", Site: "verbs.go:4512", Shape: Question},
	{Code: "carry-goal-not-live", Owner: "internal/landing", Site: "carried.go:167", Shape: Question},
	{Code: "carry-word-missing", Owner: "internal/landing", Site: "carried.go:179", Shape: Question},
	{Code: "carry-word-unproven", Owner: "internal/landing", Site: "carried.go:277", Shape: Question},
	{Code: "carry-seat-mismatch", Owner: "internal/landing", Site: "carried.go:190", Shape: Question},
	{Code: "carry-tree-mismatch", Owner: "internal/landing", Site: "carried.go:194", Shape: Question},
	{Code: "carry-not-carryable", Owner: "internal/landing", Site: "carried.go:197", Shape: Question},
	{Code: "carry-word-expired", Owner: "internal/landing", Site: "carried.go:200", Shape: Question},
	{Code: "carry-word-consumed", Owner: "internal/landing", Site: "carried.go:211", Shape: Question},
	{Code: "carry-debt-unpaid", Owner: "internal/landing", Site: "carried.go:214", Shape: Question},
	{Code: "carry-cap-reached", Owner: "internal/landing", Site: "carried.go:220", Shape: Question},
	{Code: "carry-base-judge-blind", Owner: "internal/landing", Site: "carried.go:289", Shape: Question},
	{Code: "carry-battery-unverified", Owner: "internal/landing", Site: "carried.go:236", Shape: Question},
	{Code: "carry-unneeded", Owner: "internal/landing", Site: "carried.go:257", Shape: Question},
	{Code: "carry-refusal-mismatch", Owner: "internal/landing", Site: "carried.go:182", Shape: Question},
	{Code: "STOP_SURFACE_GOAL_REFUSED", Owner: "internal/audit", Site: "stopsurface.go:666", Shape: Question},
}

var Exclusions = []Exclusion{
	{Pattern: "trunk-red-record-refused", Reason: "a batch history verb rather than a refusal returned to a caller"},
	{Pattern: "admission-refused", Reason: "a durable batch proof status rather than a refusal returned to a caller"},
	{Pattern: "budget-refused", Reason: "a durable batch history detail rather than a refusal returned to a caller"},
	{Pattern: "prove-refused", Reason: "a durable batch history verb rather than a refusal returned to a caller"},
	{Pattern: "FETCH_HEAD", Reason: "Git's fetched-head pseudoref"},
	{Pattern: "GIT_*", Reason: "git environment variable names"},
	{Pattern: "METASYSTEM_*", Reason: "this tree's environment variable names"},
	{Pattern: "BASH_SOURCE", Reason: "an environment name"},
	{Pattern: "LC_ALL", Reason: "an environment name"},
	{Pattern: "CGO_ENABLED", Reason: "a Go toolchain environment name"},
	{Pattern: "STATICCHECK_CACHE", Reason: "a Go toolchain environment name"},
	{Pattern: "JAVA_HOME", Reason: "a Java toolchain environment name"},
	{Pattern: "STEWARD_MESSAGE", Reason: "an environment name"},
	{Pattern: "HUMAN_AUTHORITY_PROVEN", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "TEMPORARY_HUMAN_WORD", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "AUTHENTICATED_CHANNEL_WORD", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "VERIFIED_CHANNEL_ANSWER", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "POWER_OF_ATTORNEY", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "AUTO_HEAL_ELIGIBLE", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "DEADLINE_EXPIRED", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "AUTO_HEAL_ENDED", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "HEALING_FLAPPING", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "NO_LAWFUL_REMEDY", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "BREACH_STOP_COMPLETE", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "BREACH_STOP_INDETERMINATE", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "BREACH_STOP_OPEN", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "ASSUMPTION_DRIFT", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "BUDGET_MISSING", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "DURABILITY_PENDING", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "INTERRUPTED_BY_NEXT_TURN", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "ENROLLMENT_CHANGED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "ENROLLMENT_DRIFT", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "NOT_ENROLLED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "NO_ADAPTER", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "FETCH_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "STATE_WRITE_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "RENDER_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "TICK_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "WRITE_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "PASS_COMPLETE", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "PASS_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "TRANSPORT_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "TRANSPORT_SUBMITTED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "ledger-unreadable", Reason: "a turn-verdict digest sentinel the steward compares, not a refusal code"},
	{Pattern: "row-unreadable", Reason: "a Stop-verdict wait-drop reason branch, not a refusal code"},
	{Pattern: "LOCAL_PENDING", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "LOCAL_TERMINAL", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "FOREIGN_REPORT_ONLY", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "ALREADY_TERMINAL", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "TERMINAL_DURING_STOP", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "MIGRATION_EPOCH", Reason: "a manifest key"},
	{Pattern: "REVIEWED_SOURCE_SHA256", Reason: "a manifest key"},
	{Pattern: "NON_NEGATIVE_INTEGER", Reason: "a usage-line placeholder"},
	{Pattern: "POSITIVE_INTEGER", Reason: "a usage-line placeholder"},
	{Pattern: "usage-unavailable", Reason: "an adapter verb name rather than a refusal"},
	{Pattern: "READY_FOR_RUNTIME", Reason: "a design-obligation status rather than a refusal"},
	{Pattern: "CONFIG_READY", Reason: "a runtime setup configuration-readiness status rather than a refusal"},
	{Pattern: "TEST_CONTRACT_READY", Reason: "a runtime setup test-contract readiness status rather than a refusal"},
	{Pattern: "PROVIDER_TRUST", Reason: "a runtime setup provider-trust status rather than a refusal"},
	{Pattern: "LIFECYCLE_OBSERVED", Reason: "a runtime setup lifecycle-observation status rather than a refusal"},
	{Pattern: "creator-identity-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "custody-entry-malformed", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "group-membership-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "index-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "indexed-record-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "prefork-group-membership-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "prefork-marker-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "prefork-process-table-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "prefork-supervisor-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "process-enumeration-unavailable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "process-table-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "recorded-identity-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "registry-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "tag-position-proof-unavailable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
}

var ShellRows = []Shell{
	{Script: "land.sh", Line: "94", Prose: "land refused: unknown option: $1", Override: "the usage line"},
	{Script: "land.sh", Line: "105", Prose: "Usage: scripts/agents/land.sh -m <message-file-or-heredoc> --goal <id> --carried <opid> [ordinary declarations]", Override: "the usage line"},
	{Script: "land.sh", Line: "107", Prose: "land refused: --staged-only cannot be combined with pathspecs", Override: "the usage line"},
	{Script: "land.sh", Line: "111", Prose: "land refused: name pathspecs or choose --staged-only", Override: "the usage line"},
	{Script: "commit.sh", Line: "234", Prose: "agent commit refused: staged Go package coverage check failed (legacy branch, contract off)", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "271", Prose: "agent commit refused: the static re-proof failed (go-gate.sh --fast; legacy branch, contract off)", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "386", Prose: "agent commit refused: the static re-proof failed (audit-metasystem.sh; legacy branch, contract off)", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "450", Prose: "agent commit refused: the landing evaluator failed or returned an incomplete decision ($landing_verdict)", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "542", Prose: "agent commit refused: the final commit message did not contain exactly one byte-exact Goal-Item stamped by --goal; the commit was rolled back", Record: true},
	{Script: "land.sh", Line: "340", Prose: "carry asks: the carried landing lands main; you are on $branch", Override: "checkout main and rerun"},
	{Script: "land.sh", Line: "605", Prose: "goal fetch returned no accepted ledger tip: $output", Override: "goal fetch then rerun"},
	{Script: "land.sh", Line: "645", Prose: "rebase conflict on <paths>; resolve by hand against origin/main, stage, rerun", Override: "resolve and rerun"},
	{Script: "land.sh", Line: "774", Prose: "origin moved during the push; rerun land.sh --carried <opid>", Override: "land.sh --carried"},
	{Script: "land.sh", Line: "794", Prose: "word <opid> was superseded by <new>; land under it: land.sh --carried <new>", Override: "land.sh --carried"},
	{Script: "land.sh", Line: "840", Prose: "word <opid> expired; issue a fresh goal carry", Override: "goal carry"},
	{Script: "land.sh", Line: "841", Prose: "carry word <opid> is missing on goal <goal>; fetch the ledger", Override: "goal fetch"},
	{Script: "commit.sh", Line: "602", Prose: "no live or base judge decided; rebuild and arm an engine at a good commit with steward arm", Override: "steward arm"},
	{Script: "commit.sh", Line: "222", Prose: "commit refused: Machine is stamped by the wrapper, never typed", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "56", Prose: "agent commit refused: the lease holder has a claim epoch but no owner lineage; export METASYSTEM_OWNER_LINEAGE in the seat's shell", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "728", Prose: "agent commit refused: the Goal-Item's claim revision moved since this chain was dispatched ($landing_verdict)", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "732", Prose: "agent commit refused: this landing names no goal and the ledger is not Goal-free ($landing_verdict)", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "736", Prose: "agent commit refused: the chain was dispatched under a different goal than --goal names ($landing_verdict)", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "951", Prose: "landing push refused: origin could not be fetched; the commit stands locally", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "930", Prose: "agent commit refused: the final commit message did not contain exactly one byte-exact Goal-Item stamped by --goal; the commit was rolled back; expected exactly one Machine trailer, found $postcondition_count", Override: "land.sh --carried"},
	{Script: "commit.sh", Line: "932", Prose: "agent commit refused: the final commit message did not contain exactly one byte-exact Goal-Item stamped by --goal; the commit was rolled back; expected exactly one Goal-Revision trailer, found $postcondition_count", Override: "land.sh --carried"},
}

var Defects = []Defect{
	{Code: "GOAL_SPLIT_REFUSED", Why: "no human verb clears the sliced mark; the only path is park plus new goals"},
}

var Slow = []string{
	"goal edit --tier 2 --why: 3 commands",
	"goal classify-sweep or goal unapprove, goal edit --risk, goal approve: 3 commands",
}
