// Package refusal holds the refusal register defined by the human-carried-landing design at HCL-AUDIT-03; refusals that carry no code are recorded by hand at their emitting site, and no test proves that list complete.
//
// Every refusal a person reads by default follows "Messages a Person Reads"
// (docs/design/design-principles.md): line 1 is what happened and the
// concrete reason in plain words, about 100 characters at most; line 2 is the
// one command that resolves it, with every value the engine knows filled in
// (or an explicit "nothing to do"). A row's Code, its Site and every other
// internal term (proof, yield, caller class, lineage, epoch, generation, opid,
// digest) appear only with --verbose or in --json, never in the default text.
package refusal

// CarriedLanding is the human verb that carries a landing past an agent
// refusal: the person's exceptional landing through the public work land,
// which records the exception and lands under it in one command.
const CarriedLanding = "work land G --exception CODE --reason R --by NAME"

// UsingException lands under an exception the person already recorded.
const UsingException = "work land G --using-exception X"

type Shape string

const (
	Identity Shape = "identity" // The machine establishes that the word is the human's.
	Warning  Shape = "warning"  // The machine prints and records the warning, then complies.
	Question Shape = "question" // The word is stale or names nothing, so the machine asks.
	Agent    Shape = "agent"    // The refusal binds an agent's act only; Override is the human verb past it.
)

type Row struct {
	Code        string // The token exactly as the walk collects it.
	Owner       string // The package or script that emits it.
	Site        string // An anchor, file#Symbol, naming the declaration that emits the code (anchor.go).
	Shape       Shape
	Override    string   // The human verb that carries past it; empty only for Identity and Question.
	Commands    int      // Commands between the human's intent and the effect; zero when Override is empty.
	Pending     string   // "human-carried-landing" while the Override is not yet in the tree.
	H1          Standing // Rule H1 standing; required for Question rows (see h1.go).
	Forward     string   // For StandingGuide: the public OBJECT ACTION the message names as "metasystem OBJECT ACTION".
	ForwardSite string   // Module-relative file#Symbol anchor emitting Forward when the Site only relays it.
}

type Exclusion struct {
	Pattern string // An exact token, or "PREFIX_*" for a prefix.
	Reason  string
}

// Prose is a refusal without a code: Owner and the Site anchor name the
// declaration that emits it (the landing path's refusals, formerly
// commit.sh's and land.sh's).
type Prose struct {
	Owner, Site, Prose, Override string
	Record                       bool // true only for a non-overridable record failure.
}

type Defect struct{ Code, Why string }

var Rows = []Row{
	{Code: "BUILD_DESIGN_NOT_ACCEPTED", Owner: "cmd/metasystem", Site: "intent_work.go#runIntentBuildUnit", Shape: Warning, Override: "goal allow G build-without-design --reason TEXT", Commands: 1, H1: StandingAgent},
	{Code: "TEST_WORKER_POLICY_UNSUPPORTED", Owner: "internal/testrun", Site: "worker.go#ErrWorkerPolicyUnsupported", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_ALREADY_SUPERVISED", Owner: "internal/launch", Site: "launch.go#Manager.Supervise", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_SETTING_INVALID", Owner: "internal/launch", Site: "settings.go#resolveSettings", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_BRIEF_OVERSIZE", Owner: "internal/launch", Site: "admit.go#Manager.admit", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_BRIEF_PACK_UNFILLED", Owner: "internal/launch", Site: "pack.go#Manager.CheckPack", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_BRIEF_PACK_DRIFTED", Owner: "internal/launch", Site: "pack.go#packDrift", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_BUILD_UNSIZED", Owner: "internal/launch", Site: "admit.go#buildSize", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_BUILD_OVERSIZE", Owner: "internal/launch", Site: "admit.go#Manager.admit", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_READ_UNSIZED", Owner: "internal/launch", Site: "admit.go#Manager.admit", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_READ_UNSPLIT", Owner: "internal/launch", Site: "admit.go#Manager.admit", Shape: Question, H1: StandingInput},
	{Code: "LAUNCH_UNIT_GOAL_BRANCH_REQUIRED", Owner: "internal/launch", Site: "unit_run.go#UnitRunner.requireGoalBranch", Shape: Question, H1: StandingInput},
	{Code: "RECEIPT_USAGE_INCOMPLETE", Owner: "internal/receipt", Site: "receipt.go#incompleteUsage", Shape: Question, H1: StandingInput},
	{Code: "UNIT_PLAN_INVALID", Owner: "internal/launch", Site: "unit_plan.go#planInvalid", Shape: Question, H1: StandingInput},
	{Code: "READ_REQUEST_INVALID", Owner: "internal/launch", Site: "standalone_read.go#UnitRunner.StartRead", Shape: Question, H1: StandingInput},
	{Code: "record-writer-refused", Owner: "cmd/metasystem", Site: "intent_delivery.go#recordWriterAdmits", Shape: Agent, Override: "review --dispositions", Commands: 1},
	{Code: "UNIT_REVISION_CONFLICT", Owner: "cmd/metasystem", Site: "intent_selection.go#runIntentRevise", Shape: Question, H1: StandingInput},
	{Code: "READ_INPUT_MISSING", Owner: "internal/launch", Site: "standalone_read.go#UnitRunner.StartRead", Shape: Question, H1: StandingInput},
	{Code: "READ_RETRY_RUNNING", Owner: "internal/launch", Site: "standalone_read.go#UnitRunner.rejoinRead", Shape: Question, H1: StandingInput},
	{Code: "READ_RETRY_UNKNOWN", Owner: "internal/launch", Site: "standalone_read.go#UnitRunner.StartRead", Shape: Question, H1: StandingInput},
	{Code: "READ_PATCH_UNREADABLE", Owner: "internal/launch", Site: "standalone_read.go#UnitRunner.StartRead", Shape: Question, H1: StandingInput},
	{Code: "UNIT_ROUND_LIMIT", Owner: "cmd/metasystem", Site: "intent_selection.go#runIntentRevise", Shape: Agent, Override: "budget", Commands: 1, H1: StandingGuide, Forward: "goal budget"},
	{Code: "carried-receipt-refused", Owner: "internal/landing", Site: "carried_prepare.go#carriedReceiptLine", Shape: Question, H1: StandingInput},
	{Code: "READ_BUSY", Owner: "internal/launch", Site: "standalone_read.go#UnitRunner.readLock", Shape: Question, H1: StandingInput},
	{Code: "READ_CHECKOUT_UNAVAILABLE", Owner: "internal/launch", Site: "standalone_read.go#UnitRunner.StartRead", Shape: Question, H1: StandingInput},
	{Code: "DESIGN_CHAIN_OPEN", Owner: "internal/dispatch", Site: "read_admission.go#CritiqueReadAdmissionForGoal", Shape: Question, H1: StandingInput},
	{Code: "READ_BRIEF_MISSING", Owner: "internal/launch", Site: "standalone_read.go#UnitRunner.StartRead", Shape: Question, H1: StandingInput},
	{Code: "UNIT_RUN_BUSY", Owner: "internal/launch", Site: "unit_run.go#UnitRunner.lock", Shape: Question, H1: StandingInput},
	{Code: "UNIT_LOCK_FAILED", Owner: "internal/launch", Site: "unit_run.go#UnitRunner.lock", Shape: Question, H1: StandingInput},
	{Code: "UNIT_RUN_NOT_AWAITING", Owner: "internal/launch", Site: "unit_run.go#admitFollowUp", Shape: Question, H1: StandingInput},
	{Code: "UNIT_FOLLOW_UP_MISSING", Owner: "internal/launch", Site: "unit_run.go#admitFollowUp", Shape: Question, H1: StandingInput},
	{Code: "UNIT_NAMED_INPUT_CHANGED", Owner: "internal/launch", Site: "unit_named.go#namedBinding.verify", Shape: Question, H1: StandingInput},
	{Code: "UNIT_RUN_UNKNOWN", Owner: "internal/launch", Site: "unit_review.go#UnitRunner.ReviewSubject", Shape: Question, H1: StandingInput},
	{Code: "UNIT_REVIEW_NOT_READY", Owner: "internal/launch", Site: "unit_review.go#UnitRunner.ReviewSubject", Shape: Question, H1: StandingInput},
	{Code: "UNIT_RESULT_CHANGED", Owner: "internal/launch", Site: "unit_review.go#UnitRunner.ReviewSubject", Shape: Question, H1: StandingInput},
	{Code: "UNIT_SUBJECT_CONFLICT", Owner: "cmd/metasystem", Site: "intent_unit_review.go#intentInvocation.reviewUnitRound", Shape: Question, H1: StandingInput},
	{Code: "BOARD_NAME_UNSAFE", Owner: "internal/board", Site: "card.go#checkName", Shape: Question, H1: StandingInput},
	{Code: "BOARD_PATH_NOT_A_DIRECTORY", Owner: "internal/board", Site: "card.go#notADirectory", Shape: Question, H1: StandingInput},
	{Code: "BOARD_UNREADABLE", Owner: "internal/board", Site: "board.go#Read", Shape: Question, H1: StandingInput},
	{Code: "LANDING_LANE_MISMATCH", Owner: "internal/landing/lane", Site: "lane.go#mismatchRefusal", Shape: Question, H1: StandingGuide, Forward: "settings set"},
	{Code: "LANDING_LANE_GONE", Owner: "internal/landing/lane", Site: "lane.go#goneRefusal", Shape: Question, H1: StandingGuide, Forward: "landing set"},
	{Code: "LANDING_LANE_REGISTER_INVALID", Owner: "internal/landing/lane", Site: "lane.go#Register", Shape: Question, H1: StandingInput},
	{Code: "LANDING_LANE_UNARMED", Owner: "internal/landing/lane", Site: "pause.go#UnarmedRefusal", Shape: Question, H1: StandingGuide, Forward: "system start"},
	{Code: "LANDING_LANE_NO_MACHINE", Owner: "internal/landing/lane", Site: "pause.go#NoMachineRefusal", Shape: Question, H1: StandingInput},
	{Code: "LANDING_LANE_RECORD_INCOMPLETE", Owner: "internal/landing/lane", Site: "lane.go#incompleteRefusal", Shape: Question, H1: StandingGuide, Forward: "landing set"},
	{Code: "LANDING_LANE_UNREACHABLE", Owner: "internal/landing/lane", Site: "unset.go#unreachableRefusal", Shape: Question, H1: StandingGuide, Forward: "landing unset"},
	{Code: "LANE_PUSH_UNPROVEN", Owner: "internal/landing/plain", Site: "push.go#provenGreen", Shape: Question, H1: StandingAgent},
	{Code: "LANE_PUSH_RED", Owner: "internal/landing/plain", Site: "push.go#provenGreen", Shape: Question, H1: StandingAgent},
	{Code: "LANE_PUSH_NOT_FAST_FORWARD", Owner: "internal/landing/plain", Site: "push.go#Push", Shape: Question, H1: StandingAgent},
	{Code: "LANDING_LANE_UNSETTING", Owner: "internal/landing/lane", Site: "unset.go#unsettingRefusal", Shape: Question, H1: StandingGuide, Forward: "landing unset"},
	{Code: "MACHINE_ON_ANOTHER_COMPUTER", Owner: "cmd/metasystem", Site: "intent_machine.go#intentInvocation.matchMachine", Shape: Question, H1: StandingGuide, Forward: "system stop"},
	{Code: "BRIDGE_SOCKET_PATH_OCCUPIED", Owner: "internal/board", Site: "bridge.go#Listen", Shape: Question, H1: StandingInput},
	{Code: "BRIDGE_SOCKET_PATH_TOO_LONG", Owner: "internal/board", Site: "bridge.go#Listen", Shape: Question, H1: StandingInput},
	{Code: "AGENT_ASK_TARGET_UNKNOWN", Owner: "cmd/metasystem", Site: "intent_agent.go#agentTargetUnknown", Shape: Question, H1: StandingInput},
	{Code: "AGENT_ASK_GOAL_UNKNOWN", Owner: "cmd/metasystem", Site: "intent_agent.go#agentGoalUnknown", Shape: Question, H1: StandingInput},
	{Code: "AGENT_ASK_TEXT_TOO_LONG", Owner: "cmd/metasystem", Site: "intent_agent.go#agentPublishRefusal", Shape: Question, H1: StandingInput},
	{Code: "AGENT_ASK_ID_TAKEN", Owner: "cmd/metasystem", Site: "intent_agent.go#agentPublishRefusal", Shape: Question, H1: StandingInput},
	{Code: "AGENT_REPLY_THREAD_UNKNOWN", Owner: "cmd/metasystem", Site: "intent_agent.go#agentThreadUnknown", Shape: Question, H1: StandingInput},
	{Code: "LANDING_WAITS_FOR_HUMAN", Owner: "internal/goal", Site: "landgate.go#Gate", Shape: Agent, Override: "goal land-without-sitting", Commands: 1, H1: StandingGuide, Forward: "goal land-without-sitting"},
	{Code: "LANDING_HELD_BY_SITTING", Owner: "internal/goal", Site: "landgate.go#Gate", Shape: Question, H1: StandingGuide, Forward: "goal review"},
	{Code: "BATCH_MEMBER_BUDGET_REFUSED", Owner: "cmd/metasystem", Site: "proof_run.go#batchMemberBudgetRefused", Shape: Question, H1: StandingGuide, Forward: "goal budget"},
	{Code: "GOAL_REVISION_MOVED", Owner: "cmd/metasystem", Site: "proof_run.go#goalRevisionMoved", Shape: Question, H1: StandingInput},
	{Code: "CANDIDATE_GOAL_MOVED", Owner: "cmd/metasystem", Site: "proof_run.go#proofAdmissionMoved", Shape: Question, H1: StandingInput},
	{Code: "CANDIDATE_GOAL_REFUSED", Owner: "cmd/metasystem", Site: "proof_run.go#candidateGoalRefusal", Shape: Question, H1: StandingInput},
	{Code: "PROOF_AUTHORITY_REQUIRED", Owner: "cmd/metasystem", Site: "proof_run.go#proofAuthorityRefusal", Shape: Question, H1: StandingAgent},
	{Code: "PROOF_AUTHORITY_ARC_MATE_REFUSED", Owner: "cmd/metasystem", Site: "proof_run.go#arcMateRefusal", Shape: Question, H1: StandingInput},
	{Code: "GOAL_DONE_READ_ITEMS_OPEN", Owner: "internal/goal", Site: "readitems.go#DoneReadItemsOpenError.RefusalCode", Shape: Question, H1: StandingGuide, Forward: "goal notes", ForwardSite: "internal/goal/readitems.go#DoneReadItemsOpenError.Error"},
	{Code: "TRUNK_RED_UNKNOWN", Owner: "internal/goal", Site: "trunkred.go#trunkRedClearRequest", Shape: Question, H1: StandingInput},
	{Code: "TRUNK_RED_CLOSED", Owner: "internal/goal", Site: "trunkred.go#trunkRedClearRequest", Shape: Question, H1: StandingInput},
	{Code: "TRUNK_RED_CHANGED", Owner: "internal/goal", Site: "trunkred.go#trunkRedClearRequest", Shape: Question, H1: StandingInput},
	{Code: "TRUNK_RED_FIX_GOAL_UNKNOWN", Owner: "internal/goal", Site: "trunkred.go#trunkRedOwnRequest", Shape: Question, H1: StandingInput},
	{Code: "TRUNK_RED_OWNED_ELSEWHERE", Owner: "internal/goal", Site: "trunkred.go#trunkRedOwnRequest", Shape: Agent, Override: "incident claim --by", Commands: 1},
	{Code: "TRUNK_RED_FLAKE_NEEDS_MAIN", Owner: "internal/goal", Site: "trunkred.go#validateTrunkRedRecordClass", Shape: Question, H1: StandingInput},
	{Code: "TRUNK_RED_PASS_NOT_EXECUTED", Owner: "internal/goal", Site: "trunkred.go#countFlakePass", Shape: Question, H1: StandingInput},
	{Code: "TRUNK_RED_FIX_UNPROVEN", Owner: "internal/goal", Site: "trunkred.go#countFlakePass", Shape: Question, H1: StandingInput},
	{Code: "TRUNK_RED_CLOSE_IS_HUMAN", Owner: "internal/goal", Site: "trunkred.go#CloseTrunkRed", Shape: Agent, Override: "incident close --reason --by", Commands: 1},
	{Code: "AGENT_IN_AUTHORITY_CHAIN", Owner: "internal/humanauthority", Site: "authority.go#walkProcessTree", Shape: Identity},
	{Code: "ANCESTRY_CHANGED", Owner: "internal/humanauthority", Site: "authority.go#stableRead", Shape: Identity},
	{Code: "ANCESTRY_CYCLE", Owner: "internal/humanauthority", Site: "authority.go#walkProcessTree", Shape: Identity},
	{Code: "ANCESTRY_UNREADABLE", Owner: "internal/humanauthority", Site: "authority.go#stableRead", Shape: Identity},
	{Code: "ARGV_UNREADABLE", Owner: "internal/humanauthority", Site: "authority.go#stableRead", Shape: Identity},
	{Code: "PROCESS_REUSED", Owner: "internal/humanauthority", Site: "authority.go#stableRead", Shape: Identity},
	{Code: "TERMINAL_NOT_ENROLLED", Owner: "internal/humanauthority", Site: "authority.go#Prove", Shape: Identity},
	{Code: "TERMINAL_NOT_REACHED", Owner: "internal/humanauthority", Site: "authority.go#ProveTerminal", Shape: Identity},

	{Code: "BRAIN_REFUSED", Owner: "cmd/metasystem", Site: "delegate.go#runDelegateWith", Shape: Agent, Override: "brain withdraw", Commands: 1},
	{Code: "CONTEXT_EVIDENCE_RETIRED", Owner: "internal/steward", Site: "contextreport.go#ContextEvidenceRetiredError.RefusalCode", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_HUMAN_UNPROVEN", Owner: "internal/steward", Site: "handoff_capture.go#handoffHumanRefusal", Shape: Identity},
	{Code: "HANDOFF_DELEGATES_UNDECLARED", Owner: "cmd/metasystem", Site: "context_verbs.go#contextHandoffDelegates", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_DELEGATE_INCOMPLETE", Owner: "cmd/metasystem", Site: "context_verbs.go#contextHandoffDelegates", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_DELEGATE_OUTPUT_MISMATCH", Owner: "cmd/metasystem", Site: "context_verbs.go#contextHandoffDelegates", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_DELEGATE_UNDECLARED", Owner: "cmd/metasystem", Site: "context_verbs.go#contextHandoffDelegates", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_DELEGATE_UNKNOWN", Owner: "cmd/metasystem", Site: "context_verbs.go#contextHandoffDelegates", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_LAUNCH_IN_FLIGHT", Owner: "internal/steward", Site: "handoff_capture.go#captureHandoffJobs", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_NOTE_LACKS_OUTPUT", Owner: "internal/steward", Site: "handoff_capture.go#captureLessonsNote", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_NOTE_MISSING", Owner: "internal/steward", Site: "handoff_capture.go#captureLessonsNote", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_NOTE_OUTSIDE_MEMORY", Owner: "internal/steward", Site: "handoff_capture.go#captureLessonsNote", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_NOTE_STALE", Owner: "internal/steward", Site: "handoff_capture.go#captureLessonsNote", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_NOT_FOUND", Owner: "internal/steward", Site: "handoff_capture.go#handoffIntentForVerification", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_NOT_HOLDER", Owner: "internal/steward", Site: "handoff_capture.go#activeDelegateCaller", Shape: Question, H1: StandingIdentity},
	{Code: "HANDOFF_NOT_LIVE", Owner: "internal/steward", Site: "handoff_capture.go#CancelHandoff", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_NO_GOAL", Owner: "internal/steward", Site: "handoff_capture.go#selectHandoffGoalWithReader", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_OTHER_SESSION", Owner: "internal/steward", Site: "handoff_capture.go#handoffCancelReason", Shape: Agent, Override: "metasystem session handoff --root <installation> --cancel <nonce> --by <human>, typed at an enrolled or agent-free terminal", Commands: 1},
	{Code: "HANDOFF_OTHER_PENDING", Owner: "internal/steward", Site: "handoff_capture.go#handoffWithGoalReader", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_REFERENCE", Owner: "internal/steward", Site: "handoff_capture.go#readStableSource", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_STATE_MISMATCH", Owner: "internal/steward", Site: "handoff_capture.go#VerifyHandoffState", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_STATE_TOO_LARGE", Owner: "internal/steward", Site: "handoff_capture.go#fitHandoffState", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_TASKS_IN_FLIGHT", Owner: "cmd/metasystem", Site: "context_verbs.go#contextHandoffDelegates", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_UNOBSERVABLE", Owner: "internal/steward", Site: "handoff_capture.go#requireObservableHandoffRuntime", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_WAIT_IN_FLIGHT", Owner: "internal/steward", Site: "handoff_capture.go#waiterInFlight", Shape: Question, H1: StandingInput},
	{Code: "HANDOFF_WAIT_UNENDABLE", Owner: "internal/steward", Site: "handoff_waits.go#EndInFlightWaits", Shape: Question, H1: StandingInput},

	{Code: "APPROVAL_REQUIRED", Owner: "internal/goal", Site: "approval.go#approvalRequired", Shape: Agent, Override: "goal approve", Commands: 1},
	{Code: "APPROVAL_EXPIRED", Owner: "internal/goal", Site: "approval.go#requireApprovedForClaimWithContext", Shape: Agent, Override: "goal approve", Commands: 1},
	{Code: "RELAY_AFTER_ENROLLMENT", Owner: "internal/goal", Site: "approval.go#refuseRelayedAfterFleetEnrollment", Shape: Identity},
	{Code: "GOAL_NORM_REFUSED", Owner: "internal/goal", Site: "norm.go#refuseGoalNorm", Shape: Agent, Override: "goal budget then --approved-ref", Commands: 2},
	{Code: "GOAL_APPROVED_REF_REFUSED", Owner: "internal/goal", Site: "norm.go#goalNormApproval", Shape: Question, H1: StandingInput},
	{Code: "GOAL_BRANCH_RANGE", Owner: "internal/goal/branch", Site: "range.go#rangeRefusal", Shape: Question, H1: StandingInput},
	{Code: "GOAL_BRANCH_ENDPOINT_UNSUPPORTED", Owner: "internal/goal/branch", Site: "park.go#mainEndpoint", Shape: Question, H1: StandingInput},
	{Code: "GOAL_BRANCH_UNAVAILABLE", Owner: "internal/goal/branch", Site: "commit.go#CheckCommitAccess", Shape: Question, H1: StandingInput},
	{Code: "GOAL_BRANCH_NOT_HOLDER", Owner: "internal/goal/branch", Site: "commit.go#checkClaim", Shape: Question, H1: StandingGuide, Forward: "goal claim", ForwardSite: "cmd/metasystem/goal_branch.go#goalHeldElsewhere.Error"},
	{Code: "GOAL_BRANCH_LEASE_MOVED", Owner: "internal/goal/branch", Site: "push.go#reconcilePushTransactionsWithRepository", Shape: Question, H1: StandingInput},
	{Code: "GOAL_BRANCH_CLAIM_LOST", Owner: "internal/goal/branch", Site: "push.go#reconcilePushTransactionsWithRepository", Shape: Question, H1: StandingAgent},
	{Code: "GOAL_BRANCH_PUSH_UNKNOWN", Owner: "internal/goal/branch", Site: "push.go#reconcilePushTransactionsWithRepository", Shape: Question, H1: StandingInput},
	{Code: "GOAL_BRANCH_STALE", Owner: "internal/goal/branch", Site: "push.go#adoptRemoteTipWithRepository", Shape: Question, H1: StandingInput},
	{Code: "GOAL_PARK_UNPUSHED", Owner: "internal/goal/branch", Site: "status.go#checkParkBranch", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_PARTIAL", Owner: "internal/goal/branch", Site: "land.go#prepareLanding", Shape: Question, H1: StandingInput},
	{Code: "GOAL_UNIT_REREAD", Owner: "internal/goal/branch", Site: "land.go#verifyUnitPreimagesWith", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_UNPROVEN", Owner: "internal/goal/branch", Site: "land.go#readLandingReceiptWith", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_RETRY", Owner: "internal/goal/branch", Site: "land.go#prepareLanding", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_UNCHECKED", Owner: "internal/goal/branch", Site: "land.go#prepareLanding", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_BRANCH_MOVED", Owner: "internal/goal/branch", Site: "land.go#prepareLanding", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_TRUNK_MOVED", Owner: "internal/goal/branch", Site: "publish.go#landPushWithRepository", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_VERIFY", Owner: "internal/goal/branch", Site: "verify.go#landedManifestWithGit", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_AUTHOR_UNBOUND", Owner: "internal/goal/branch", Site: "land.go#resolveLandingIdentityWith", Shape: Question, H1: StandingInput},
	{Code: "GOAL_LAND_TRUNK_RED", Owner: "internal/goal/branch", Site: "red.go#HandleLandingRed", Shape: Question, H1: StandingInput},
	{Code: "GOAL_SWEEP_UNLANDED", Owner: "internal/goal/branch", Site: "sweep.go#checkSweepTipWith", Shape: Question, H1: StandingInput},
	{Code: "GOAL_READ_UNGATED", Owner: "internal/goal/branch", Site: "attest.go#validateAttestation", Shape: Question, H1: StandingInput},
	{Code: "GOAL_READ_TESTS_UNNAMED", Owner: "internal/goal/branch", Site: "attest.go#validateTestChangesWithReads", Shape: Question, H1: StandingInput},
	{Code: "GOAL_READ_STALE", Owner: "internal/goal/branch", Site: "attest.go#validateAttestation", Shape: Question, H1: StandingInput},
	{Code: "GOAL_READ_DISPATCH_PENDING", Owner: "internal/goal/branch", Site: "read.go#saveBranchReadRecord", Shape: Question, H1: StandingInput},
	{Code: "GOAL_READ_INVALID", Owner: "internal/goal/branch", Site: "attest.go#foldRangeWithReads", Shape: Question, H1: StandingInput},
	{Code: "GOAL_READ_BRIEF_CHANGED", Owner: "internal/goal/branch", Site: "read.go#RunBranchRead", Shape: Question, H1: StandingInput},
	{Code: "attested-malformed-id", Owner: "internal/landing", Site: "attested.go#observeAttestedWithFacts", Shape: Question, H1: StandingInput},
	{Code: "attested-unreadable", Owner: "internal/landing", Site: "attested.go#attestedBindingCode", Shape: Question, H1: StandingInput},
	{Code: "attested-invalid", Owner: "internal/landing", Site: "attested.go#attestedBindingCode", Shape: Question, H1: StandingInput},
	{Code: "attested-not-critic", Owner: "internal/landing", Site: "attested.go#observeAttestedWithFacts", Shape: Question, H1: StandingInput},
	{Code: "attested-goal-mismatch", Owner: "internal/landing", Site: "attested.go#attestedBindingCode", Shape: Question, H1: StandingInput},
	{Code: "attested-change-mismatch", Owner: "internal/landing", Site: "attested.go#attestedBindingCode", Shape: Question, H1: StandingInput},
	{Code: "attested-not-design-bearing", Owner: "internal/landing", Site: "attested.go#observeAttestedWithFacts", Shape: Question, H1: StandingInput},
	{Code: "GOAL_SPLIT_REFUSED", Owner: "internal/goal", Site: "split.go#splitRequest", Shape: Agent, H1: StandingGuide, Forward: "goal done"},
	{Code: "RECONCILE_OUTSIDE_SCOPE", Owner: "internal/goal", Site: "reconcilepub.go#reconcileFor", Shape: Question, H1: StandingInput},
	{Code: "GOAL_CLAIM_QUOTA", Owner: "internal/goal", Site: "verbs.go#claimQuotaRefusal", Shape: Question, H1: StandingGuide, Forward: "goal release"},
	{Code: "REBIND_EPOCH_UNAUTHENTICATED", Owner: "internal/goal", Site: "verbs.go#ClaimEpochForRebind", Shape: Identity},
	{Code: "SET_BUDGET_FENCED_SAME_TUPLE", Owner: "internal/goal", Site: "verbs.go#setBudgetRequest", Shape: Question, H1: StandingGuide, Forward: "goal resume"},
	{Code: "SPLIT_RATIFY_REFUSED", Owner: "internal/goal", Site: "split.go#validateSplitRatification", Shape: Question, H1: StandingInput},
	{Code: "SWEEP_DUPLICATE_GOAL", Owner: "internal/goal", Site: "approval.go#classificationListing", Shape: Question, H1: StandingInput},
	{Code: "SWEEP_INCOMPLETE", Owner: "internal/goal", Site: "approval.go#classificationListing", Shape: Question, H1: StandingInput},
	{Code: "SWEEP_LISTING_CHANGED", Owner: "internal/goal", Site: "approval.go#installTierLawRequest", Shape: Question, H1: StandingInput},
	{Code: "SWEEP_MALFORMED_ROW", Owner: "internal/goal", Site: "approval.go#classificationListing", Shape: Question, H1: StandingInput},
	{Code: "SWEEP_UNKNOWN_GOAL", Owner: "internal/goal", Site: "approval.go#classificationListing", Shape: Question, H1: StandingInput},
	{Code: "ELAPSED_LIMIT", Owner: "internal/dispatch", Site: "stop.go#liveStopReason", Shape: Agent, Override: "goal resume", Commands: 1},
	{Code: "CORRUPT_OVER_LIMIT", Owner: "internal/dispatch", Site: "stop.go#liveStopReason", Shape: Agent, Override: "goal resume", Commands: 1},

	{Code: "BUDGET_UNKNOWN", Owner: "internal/dispatch", Site: "admission.go#evaluateGoalAdmissionWithReads", Shape: Agent, Override: "goal budget", Commands: 1},
	{Code: "BUDGET_REFUSED", Owner: "internal/dispatch", Site: "admission.go#FormatGoalAdmission", Shape: Agent, Override: "goal budget", Commands: 1, H1: StandingGuide, Forward: "goal budget", ForwardSite: "internal/dispatch/admission.go#budgetRaiseRemedy"},
	{Code: "CANDIDATE_EXTENSION_REFUSED", Owner: "internal/dispatch", Site: "admission.go#evaluateCandidateConsumptionAdmissionWithReads", Shape: Question, H1: StandingGuide, Forward: "goal budget"},
	{Code: "HAZARD_REFUSED", Owner: "internal/dispatch", Site: "admission.go#evaluateGoalRevisionAdmissionForDispatchWithReads", Shape: Agent, Override: "goal edit --tier 2 --why", Commands: 3},
	{Code: "RISK_UNANSWERED", Owner: "internal/dispatch", Site: "admission.go#evaluateGoalRevisionAdmissionForDispatchWithReads", Shape: Agent, Override: "goal unapprove, goal edit --risk, goal approve", Commands: 3},
	{Code: "CLOCK_REGRESSED", Owner: "internal/dispatch", Site: "budget.go#projectBudgetWithoutRun", Shape: Agent, Override: "goal budget", Commands: 1},
	{Code: "ADMISSION_CLOSED_ELAPSED", Owner: "internal/dispatch", Site: "budget.go#finishBudgetProjection", Shape: Agent, Override: "goal resume", Commands: 1},
	{Code: "ELAPSED_BREACH", Owner: "internal/steward", Site: "health.go#stopFiringEvidenceSummary", Shape: Agent, Override: "goal resume", Commands: 1},
	{Code: "BRIEF_AUTHORITY_REFUSED", Owner: "internal/dispatch", Site: "brief.go#BriefAuthorityRefusal.RefusalCode", Shape: Question, H1: StandingInput},
	{Code: "BRIEF_BOUNDS_INVALID", Owner: "internal/dispatch", Site: "brief.go#BriefBoundsRefusal.RefusalCode", Shape: Question, H1: StandingInput},
	{Code: "BRIEF_BOUNDS_UNREADABLE", Owner: "internal/validate", Site: "brief_bounds_source.go#BriefBoundsUnreadable.RefusalCode", Shape: Question, H1: StandingInput},
	{Code: "OBLIGATION_REFUSED", Owner: "internal/dispatch", Site: "governed.go#evaluateGovernedRunAdmissionWithReads", Shape: Agent, Override: "goal edit --obligation", Commands: 1, H1: StandingGuide, Forward: "goal edit"},
	{Code: "SLICE_CAP_REFUSED", Owner: "internal/dispatch", Site: "slice.go#evaluateSliceAdmissionWithReads", Shape: Agent, Override: "goal approve or goal budget, then --approved-ref", Commands: 2},
	{Code: "SLICE_START_UNRECORDED", Owner: "internal/dispatch", Site: "claim.go#markFirstSliceWithReads", Shape: Agent, Override: "goal sync --recover", Commands: 1},
	{Code: "slice-approval-refused", Owner: "internal/dispatch", Site: "claim.go#ClaimLaunch", Shape: Agent, Override: "goal approve", Commands: 1},
	{Code: "REFERENCE_MISMATCH", Owner: "internal/dispatch", Site: "references.go#ReferenceMismatch.Line", Shape: Agent, Override: "delegate (a fresh composition)", Commands: 1},
	{Code: "SUBJECT_MISMATCH", Owner: "internal/dispatch", Site: "read_subject_compute.go#checkLiveSubjectWorkspace", Shape: Agent, Override: "dispatch.sh follow-up on the implementer, validate conformance --stage review --job <that round>, dispatch the critic again", Commands: 3, H1: StandingGuide, Forward: "work revise"},
	{Code: "CONCURRENT_READ", Owner: "internal/dispatch", Site: "read_admission.go#CritiqueReadAdmissionForGoal", Shape: Agent, Override: "dispatch.sh cancel --job <outstanding critic round>, then dispatch the critic again", Commands: 2, H1: StandingGuide, Forward: "work stop"},
	{Code: "REDUNDANT_READ", Owner: "internal/dispatch", Site: "read_admission.go#redundantReadError", Shape: Agent, Override: "metasystem work finish j2:<prior critic root>", Commands: 1, H1: StandingGuide, Forward: "work finish"},
	{Code: "DELEGATE_RECEIPT_REFUSED", Owner: "internal/validate", Site: "conformance.go#conformanceRun.boundaryViolations", Shape: Agent, Override: "remove the delegate change to memory/receipts.log, then work review j2:<that round> --check-only --stage review", Commands: 2},
	{Code: "TEST_POLICY_ENGINE_REQUIRED", Owner: "internal/enginecause", Site: "cause.go#Refusal.Detail", Shape: Agent, Override: "the run: command of the line's cause (internal/enginecause.Table)", Commands: 9},
	{Code: "PARALLEL_RATCHET_REFUSED", Owner: "cmd/devgate", Site: "owners.go#parallelRatchet", Shape: Question, H1: StandingInput},
	{Code: "TEST_CONTRACT_REQUIRED", Owner: "internal/testpolicy", Site: "contract.go#Contract.Validate", Shape: Question, H1: StandingInput},
	{Code: "TEST_GROUP_SELECTION_REFUSED", Owner: "internal/testpolicy", Site: "select.go#Select", Shape: Question, H1: StandingInput},
	{Code: "RETRY_PRIOR_OUTSIDE_TREE", Owner: "internal/proofrun", Site: "attempt.go#retryPriorOutsideTree", Shape: Question, H1: StandingInput},
	{Code: "TEST_RETRY_REQUIRED", Owner: "cmd/metasystem", Site: "test.go#testRunRetryRequired", Shape: Question, H1: StandingInput},
	{Code: "ADMISSION_OVERLAP_UNKNOWN", Owner: "internal/proofrun", Site: "admission.go#AdmissionCap.RefusalReason", Shape: Question, H1: StandingInput},
	{Code: "ADMISSION_NESTING_UNKNOWN", Owner: "internal/proofrun", Site: "admission.go#AdmissionCap.RefusalReason", Shape: Question, H1: StandingInput},
	{Code: "TEST_POLICY_COVERAGE_FLOOR_LOWERED", Owner: "internal/testrun", Site: "prepare.go#protectCoverageRatchets", Shape: Question, H1: StandingGuide, Forward: "test run"},
	{Code: "TESTING_MERGE_CONFLICT", Owner: "internal/testpolicy/contractmerge", Site: "merge.go#conflict", Shape: Question, H1: StandingInput},
	{Code: "TESTING_CONTRACT_INVALID", Owner: "internal/testpolicy/contractmerge", Site: "merge.go#invalid", Shape: Question, H1: StandingInput},
	{Code: "TESTING_ADD_TESTS_REFUSED", Owner: "internal/testpolicy/contractmerge", Site: "addtests.go#addTestsRefusal", Shape: Question, H1: StandingInput},
	{Code: "TESTING_MERGE_DRIVER_UNRESOLVED", Owner: "internal/testpolicy/contractgit", Site: "driver.go#unresolved", Shape: Agent, Override: "run the verb from an installed metasystem binary", Commands: 1},
	{Code: "TESTING_MERGE_ATTRIBUTE_MISUSE", Owner: "internal/testpolicy/contractgit", Site: "transition.go#refuseMisusedAttributeWith", Shape: Question, H1: StandingInput},
	{Code: "TESTING_CONTRACT_HAND_MERGED", Owner: "internal/testpolicy/contractgit", Site: "transition.go#checkContractBytesWith", Shape: Question, H1: StandingInput},

	{Code: "advance-checkout-locked", Owner: "internal/landing", Site: "advance.go#advanceWithWorkspace", Shape: Agent, Override: "wait, then fetch, advance, push", Commands: 3},
	{Code: "advance-not-on-branch", Owner: "internal/landing", Site: "advance.go#advanceWithWorkspace", Shape: Agent, Override: "git switch <branch>; fetch, advance, push", Commands: 4},
	{Code: "advance-index-not-empty", Owner: "internal/landing", Site: "advance.go#advanceWithWorkspace", Shape: Agent, Override: "land or unstage the staged paths; fetch, advance, push", Commands: 4},
	{Code: "advance-rebase-conflict", Owner: "internal/landing", Site: "advance.go#advanceWithWorkspace", Shape: Agent, Override: "carry dirty registers first, then git rebase in the real checkout and resolve; push", Commands: 4},
	{Code: "advance-unstaged-drift", Owner: "internal/landing", Site: "advance.go#advanceWithWorkspace", Shape: Agent, Override: "land or restore the named path; fetch, advance, push", Commands: 4},
	{Code: "advance-register-removed", Owner: "internal/landing", Site: "advance.go#advanceWithWorkspace", Shape: Agent, Override: "restore the register from the upstream by hand; fetch, advance, push", Commands: 4},
	{Code: "advance-register-contended", Owner: "internal/landing", Site: "advance.go#advanceWithWorkspace", Shape: Agent, Override: "work land --direct-fix register-carriage --message FILE --path <registers>", Commands: 1},
	{Code: "advance-head-moved", Owner: "internal/landing", Site: "advance.go#advanceWithWorkspace", Shape: Agent, Override: "read git reflog <branch>; fetch, advance, push", Commands: 4},

	{Code: "malformed-candidate-tree", Owner: "internal/landing", Site: "observe.go#observeWithReader", Shape: Question, H1: StandingInput},
	{Code: "candidate-tree-unreadable", Owner: "internal/landing", Site: "observe.go#observeWithReader", Shape: Question, H1: StandingInput},
	{Code: "evaluator-unavailable", Owner: "internal/landing/landpath", Site: "commit.go#boundary.decideAndCommit", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "missing-declaration", Owner: "internal/landing", Site: "observe.go#observeWithReader", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "conflicting-declarations", Owner: "internal/landing", Site: "observe.go#observeWithReader", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "path-unclassified", Owner: "internal/landing", Site: "observe.go#nonBehaviorClassError", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "ledger-path-not-goal-verb", Owner: "internal/landing", Site: "observe.go#nonBehaviorClassError", Shape: Agent, Override: "the owning goal verb", Commands: 1},
	{Code: "runtime-path-refused", Owner: "internal/landing", Site: "observe.go#nonBehaviorClassError", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "exact-revert-record-refused", Owner: "internal/landing", Site: "observe.go#exactRevertClassError", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "goal-item-not-held", Owner: "internal/landing", Site: "observe.go#heldGoal", Shape: Agent, Override: "goal claim --take-over", Commands: 1},
	{Code: "goal-binding-missing", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "goal-binding-mismatch", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "goal-revision-moved", Owner: "internal/landing", Site: "observe.go#heldGoal", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "goal-revision-unbound", Owner: "internal/landing", Site: "held.go#heldWithFacts", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "machine-trailer-malformed", Owner: "internal/landing", Site: "held.go#heldWithFacts", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "endpoint-mismatch", Owner: "internal/landing", Site: "held.go#heldWithFacts", Shape: Agent, Override: "a human commit is sovereign; re-dispatch under the current claim", Commands: 1},
	{Code: "range-not-linear", Owner: "internal/landing", Site: "held.go#heldRange", Shape: Agent, Override: "rebase onto the fetched tip, or land through work land", Commands: 1},
	{Code: "record-not-owned", Owner: "internal/landing", Site: "observe.go#carriedLandingAppendError", Shape: Agent, Override: "goal claim of the owning goal", Commands: 1},
	{Code: "malformed-chain-id", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-record-unreadable", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-record-malformed", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-not-implementation", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-not-design-bearing", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-open", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-output-unreadable", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-output-mismatch", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-has-uncarried-paths", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-base-unproven", Owner: "internal/validate", Site: "recertification.go#conformanceRun.recertify", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-source-changed", Owner: "internal/validate", Site: "recertification.go#conformanceRun.recertify", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-overlap", Owner: "internal/validate", Site: "recertification.go#conformanceRun.recertify", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-unproven", Owner: "internal/validate", Site: "recertification.go#conformanceRun.recertify", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-worktree-incomplete", Owner: "internal/validate", Site: "recertification.go#conformanceRun.recertify", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-timeout", Owner: "internal/validate", Site: "recertification.go#recertificationLock", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-target-moved", Owner: "internal/landing", Site: "observe.go#observeWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-test-command-refused", Owner: "internal/landing", Site: "observe.go#observeWithReader", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-recertification-park-failed", Owner: "internal/landing", Site: "park.go#ParkFailure.RefusalCode", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "register-carriage-policy-unreadable", Owner: "internal/landing", Site: "observe.go#candidatePathPolicyWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "register-carriage-path-refused", Owner: "internal/landing", Site: "observe.go#nonBehaviorClassError", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "register-carriage-not-append-only", Owner: "internal/landing", Site: "observe.go#carriedCounselorAppendLines", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "malformed-revert-commit", Owner: "internal/landing", Site: "observe.go#observeDirectFixWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "direct-fix-policy-unreadable", Owner: "internal/landing", Site: "observe.go#observeDirectFixWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "not-exact-revert", Owner: "internal/landing", Site: "observe.go#exactRevertRefusalCode", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "direct-fix-floor-refused", Owner: "internal/landing", Site: "observe.go#behaviorResolvedError", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "unknown-direct-fix-class", Owner: "internal/landing", Site: "observe.go#observeDirectFixWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-full-gate-refused", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "chain-test-receipt-refused", Owner: "internal/landing", Site: "observe.go#observeChainWithFacts", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "proof-input-moved-after-receipt", Owner: "cmd/metasystem", Site: "test.go#printMovedInputsCode", Shape: Agent, Override: "reset to the pushed tip, re-stage, landing test-receipt --mode auto, land again", Commands: 4},
	{Code: "tier1-declaration-refused", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "tier1-policy-unreadable", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "tier1-root-refused", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "tier1-floor-refused", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "tier1-diff-shape-refused", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "tier1-file-bound-refused", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "tier1-line-bound-refused", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "tier1-receipt-refused", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},
	{Code: "tier1-full-gate-refused", Owner: "internal/landing", Site: "tierone.go#observeTierOne", Shape: Agent, Override: CarriedLanding, Commands: 1},

	{Code: "carry-ledger-moved", Owner: "internal/landing", Site: "carried.go#ReadCarryStatus", Shape: Question, H1: StandingInput},
	{Code: "carry-remote-required", Owner: "internal/goal", Site: "verbs.go#carryRemoteRequired", Shape: Question, H1: StandingInput},
	{Code: "carry-goal-not-live", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-word-missing", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-word-unproven", Owner: "internal/landing", Site: "carried.go#carryWordAuthorityRefusal", Shape: Question, H1: StandingInput},
	{Code: "carry-seat-mismatch", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-tree-mismatch", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-not-carryable", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-word-expired", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-word-consumed", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-debt-unpaid", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-cap-reached", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-base-judge-blind", Owner: "internal/landing", Site: "carried.go#baseJudgeFenceRefusalWithSources", Shape: Question, H1: StandingInput},
	{Code: "carry-battery-unverified", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-unneeded", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "carry-refusal-mismatch", Owner: "internal/landing", Site: "carried.go#observeCarried", Shape: Question, H1: StandingInput},
	{Code: "STOP_SURFACE_GOAL_REFUSED", Owner: "internal/audit", Site: "stopsurface.go#stopSurfaceGoalRefusal", Shape: Question, H1: StandingGuide, Forward: "goal allow", ForwardSite: "internal/audit/stopsurface.go#requireStopSurfaceGoalPermission"},
	{Code: "SEAT_MACHINE_NICKNAME_INVALID", Owner: "internal/seat", Site: "record.go#ValidateMachineName", Shape: Question, H1: StandingInput},
	{Code: "SEAT_PRESENCE_MALFORMED", Owner: "internal/seat", Site: "record.go#ParseRecord", Shape: Question, H1: StandingInput},
	{Code: "SEAT_PRESENCE_CONFLICT", Owner: "internal/seat", Site: "publish.go#Conflict", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_NICKNAME_INVALID", Owner: "internal/seat/launch", Site: "preflight.go#nickname", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_NICKNAME_TAKEN", Owner: "internal/seat/launch", Site: "preflight.go#nickname", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_DESTINATION_EXISTS", Owner: "internal/seat/launch", Site: "preflight.go#destination", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_DESTINATION_INSIDE_A_CHECKOUT", Owner: "internal/seat/launch", Site: "preflight.go#destination", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_RUNNING", Owner: "internal/seat/launch", Site: "lock.go#Take", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_DISK_SHORT", Owner: "internal/seat/launch", Site: "sequence.go#Sequencer.room", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_EVIDENCE_ROOT_UNSAFE", Owner: "internal/seat/launch", Site: "sequence.go#Sequencer.evidenceRoot", Shape: Question, H1: StandingGuide, Forward: "machine start", ForwardSite: "internal/seat/launch/refusal.go#evidenceRootCommand"},
	{Code: "SEAT_LAUNCH_WORD_REQUIRED", Owner: "internal/seat/launch", Site: "sequence.go#Sequencer.enrollment", Shape: Question, H1: StandingIdentity},
	{Code: "SEAT_LAUNCH_WORD_INVALID", Owner: "internal/seat/launch", Site: "preflight.go#Admit", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_RECORD_CONFLICT", Owner: "internal/seat/launch", Site: "preflight.go#Admit", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_ID_INVALID", Owner: "internal/seat/launch", Site: "record.go#Path", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_FLEET_UNREADABLE", Owner: "internal/seat/launch", Site: "presence.go#SeatPresence.Taken", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_SUPERVISION_DOWN", Owner: "internal/seat/launch", Site: "sequence.go#Sequencer.supervision", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_IDENTITY_UNREADABLE", Owner: "internal/seat/launch", Site: "sequence.go#Sequencer.presence", Shape: Question, H1: StandingIdentity},
	{Code: "SEAT_LAUNCH_UNKNOWN", Owner: "internal/seat/launch", Site: "record.go#Discard", Shape: Question, H1: StandingInput},
	{Code: "SEAT_LAUNCH_DISCARD_RUNNING", Owner: "internal/seat/launch", Site: "record.go#Discard", Shape: Question, H1: StandingInput},
}

var Exclusions = []Exclusion{
	{Pattern: "AUTO_MERGE", Reason: "a git state file name, not a refusal"},
	{Pattern: "MERGE_HEAD", Reason: "a git state file name, not a refusal"},
	{Pattern: "budget-malformed", Reason: "a typed health remedy cause name rather than a refusal returned to a caller"},
	{Pattern: "CLAUDE_CONFIG_DIR", Reason: "the Claude Code configuration directory environment variable, not a refusal"},
	{Pattern: "GIT_*", Reason: "git environment variable names"},
	{Pattern: "SIGNED_IN_LAUNCH_GIT_*", Reason: "environment variable names of the g1-s72 end-to-end test's Git stand-in (cmd/metasystem/testdata/signedinlaunchgit), not a refusal"},
	{Pattern: "METASYSTEM_*", Reason: "this tree's environment variable names"},
	{Pattern: "LC_ALL", Reason: "an environment name"},
	{Pattern: "LANDING_TREE", Reason: "an environment name landing prove gives the project's proof command"},
	{Pattern: "LANDING_COMMIT", Reason: "an environment name landing prove gives the project's proof command"},
	{Pattern: "COMP_*", Reason: "bash's programmable-completion variables, read by the shell completion glue (cmd/metasystem/completion.go), not a refusal"},
	{Pattern: "CGO_ENABLED", Reason: "a Go toolchain environment name"},
	{Pattern: "STATICCHECK_CACHE", Reason: "a Go toolchain environment name"},
	{Pattern: "JAVA_HOME", Reason: "a Java toolchain environment name"},
	{Pattern: "XDG_CONFIG_HOME", Reason: "an XDG base-directory environment name that proof scratch declares or isolates"},
	{Pattern: "STEWARD_MESSAGE", Reason: "an environment name"},
	{Pattern: "HUMAN_AUTHORITY_PROVEN", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "TEMPORARY_HUMAN_WORD", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "AUTHENTICATED_CHANNEL_WORD", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "VERIFIED_CHANNEL_ANSWER", Reason: "an authority outcome that admits rather than refuses"},
	{Pattern: "AUTO_HEAL_ELIGIBLE", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "DEADLINE_EXPIRED", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "AUTO_HEAL_ENDED", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "HEALING_FLAPPING", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "NO_LAWFUL_REMEDY", Reason: "a steward health observation that refuses nothing"},
	{Pattern: "BREACH_STOP_COMPLETE", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "BREACH_STOP_INDETERMINATE", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "BREACH_STOP_OPEN", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "ASSUMPTION_DRIFT", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "BUDGET_MISSING", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "DURABILITY_PENDING", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "INTERRUPTED_BY_NEXT_TURN", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "ENROLLMENT_CHANGED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "NOT_ENROLLED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "NO_ADAPTER", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "FETCH_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "STATE_WRITE_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "RENDER_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "TICK_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "WRITE_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "PASS_COMPLETE", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "PUBLISH_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "PASS_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "TRANSPORT_FAILED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "TRANSPORT_SUBMITTED", Reason: "a steward component observation that refuses nothing"},
	{Pattern: "ledger-unreadable", Reason: "a turn-verdict digest sentinel the steward compares, not a refusal code"},
	{Pattern: "row-unreadable", Reason: "a Stop-verdict wait-drop reason branch, not a refusal code"},
	{Pattern: "LOCAL_PENDING", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "LOCAL_TERMINAL", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "FOREIGN_REPORT_ONLY", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "ALREADY_TERMINAL", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "TERMINAL_DURING_STOP", Reason: "a stop-verdict state after a stop was ordered"},
	{Pattern: "MIGRATION_EPOCH", Reason: "a manifest key"},
	{Pattern: "REVIEWED_SOURCE_SHA256", Reason: "a manifest key"},
	{Pattern: "READY_FOR_RUNTIME", Reason: "a design-obligation status rather than a refusal"},
	{Pattern: "creator-identity-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "custody-entry-malformed", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "group-membership-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "index-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "indexed-record-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "prefork-group-membership-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "prefork-marker-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "prefork-process-table-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "prefork-supervisor-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "process-enumeration-unavailable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "process-table-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "recorded-identity-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "registry-unreadable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
	{Pattern: "tag-position-proof-unavailable", Reason: "a census or custody evidence code rather than a refusal returned to a caller"},
}

var ProseRows = []Prose{
	{Owner: "internal/landing/landpath", Site: "land.go#driver.validate", Prose: "--staged lands what is staged, so it takes no --path, so nothing was landed", Override: "the usage line"},
	{Owner: "internal/landing/landpath", Site: "land.go#driver.validate", Prose: "nothing to land: no --path and no --staged, so nothing was landed", Override: "the usage line"},
	{Owner: "internal/landing/landpath", Site: "commit_record.go#boundary.refuseAgent", Prose: "the landing check crashed or gave no answer, so nothing was committed", Override: CarriedLanding},
	{Owner: "internal/landing/landpath", Site: "commit_record.go#boundary.commit", Prose: "the commit was undone: its message didn't end up with exactly one Goal-Item: line", Record: true},
	{Owner: "internal/landing/landpath", Site: "land.go#driver.verifyChecks", Prose: "an exception lands main, and this checkout is on <branch>", Override: "git switch main and rerun"},
	{Owner: "internal/landing/landpath", Site: "carried.go#driver.goalFetchForCarry", Prose: "the goal records came back incomplete, so nothing was landed", Override: "goal sync then rerun"},
	{Owner: "internal/landing/landpath", Site: "carried.go#driver.carryForwardStaged", Prose: "the change conflicts with main in <paths>, so nothing was landed", Override: "resolve and rerun"},
	{Owner: "internal/landing/landpath", Site: "carried.go#driver.finishCarriedPublication", Prose: "main moved while this landed, so nothing was pushed", Override: UsingException},
	{Owner: "internal/landing/landpath", Site: "carried.go#driver.runCarried", Prose: "exception <opid> was replaced by <new>", Override: UsingException},
	{Owner: "internal/landing/landpath", Site: "carried.go#driver.runCarried", Prose: "exception <opid> has expired, so nothing was landed", Override: CarriedLanding},
	{Owner: "internal/landing/landpath", Site: "carried.go#driver.runCarried", Prose: "goal <goal> has no exception <opid>, so nothing was landed", Override: "goal sync"},
	{Owner: "internal/landing/landpath", Site: "commit.go#boundary.decideAndCommit", Prose: "neither this metasystem nor one built from HEAD could judge the landing, so nothing was committed", Override: "go run ./cmd/devgate build, then rerun"},
	{Owner: "internal/landing/landpath", Site: "commit.go#boundary.scanMessage", Prose: "the commit message types a line the landing adds itself (<trailer>:), so nothing was committed", Override: CarriedLanding},
	{Owner: "internal/landing/landpath", Site: "commit.go#boundary.held", Prose: "this agent shell doesn't say which session it is, so nothing was committed", Override: CarriedLanding},
	{Owner: "internal/landing/landpath", Site: "commit_record.go#boundary.refuseAgent", Prose: "goal <goal> was claimed again after this work started, so the work is no longer its own", Override: CarriedLanding},
	{Owner: "internal/landing/landpath", Site: "commit_record.go#boundary.refuseAgent", Prose: "this change names no goal, and landings here need one", Override: CarriedLanding},
	{Owner: "internal/landing/landpath", Site: "commit_record.go#boundary.refuseAgent", Prose: "this work was started for another goal than <goal>, so nothing was committed", Override: CarriedLanding},
	{Owner: "internal/landing/landpath", Site: "commit_record.go#boundary.push", Prose: "committed, but not pushed: origin couldn't be reached", Override: CarriedLanding},
	{Owner: "internal/landing/landpath", Site: "commit_record.go#boundary.commit", Prose: "the commit was undone: its message ended up with <count> <trailer>: lines instead of one", Override: CarriedLanding},
}

var Defects = []Defect{
	{Code: "GOAL_SPLIT_REFUSED", Why: "no human verb clears the sliced mark; the only path is park plus new goals"},
}

var Slow = []string{
	"goal edit --tier 2 --why: 3 commands",
	"goal unapprove, goal edit --risk, goal approve: 3 commands",
}
