package main

// Group 6 of the "Messages a Person Reads" rewrite: system, app, disk,
// evidence, interface and the rest. Every path here is enforced.
var _ = enforceMessages(
	"cmd/metasystem/app.go",
	"cmd/metasystem/completion.go",
	"cmd/metasystem/intent.go",
	"cmd/metasystem/intent_app.go",
	"cmd/metasystem/intent_disk.go",
	"cmd/metasystem/intent_machine.go",
	"cmd/metasystem/intent_operations.go",
	"cmd/metasystem/intent_process.go",
	"cmd/metasystem/main.go",
	"cmd/metasystem/process_verbs.go",
	"cmd/metasystem/report.go",
	"cmd/metasystem/ui_launch.go",
	"internal/adopt",
	"internal/authority",
	"internal/capability",
	"internal/census",
	// internal/config/context.go keeps CONTEXT_CONFIG_INVALID in its error:
	// the steward's health line and the context design read that code.
	"internal/config/attention.go",
	"internal/config/autoruntime.go",
	"internal/config/board.go",
	"internal/config/budget.go",
	"internal/config/conf.go",
	"internal/config/confidentity.go",
	"internal/config/defaults.go",
	"internal/config/disk.go",
	"internal/config/disksettings.go",
	"internal/config/evidenceroot.go",
	"internal/config/governance.go",
	"internal/config/landinggate.go",
	"internal/config/model.go",
	"internal/config/placement.go",
	"internal/config/resolve.go",
	"internal/config/seat.go",
	"internal/config/spend.go",
	"internal/config/template.go",
	"internal/config/ui.go",
	"internal/config/validate.go",
	"internal/counselor",
	"internal/diskstore",
	"internal/evidence",
	"internal/evidencetable",
	"internal/gocache",
	"internal/gopackages",
	"internal/governance",
	"internal/humanauthority",
	"internal/identity",
	"internal/narratordigest",
	"internal/obligationstate",
	"internal/project",
	"internal/readsubject",
	"internal/registry",
	"internal/report",
	"internal/ui/act",
	"internal/ui/httpd/walkthrough",
	"internal/ui/partner",
	"internal/ui/uihome",
	"internal/usage",
)
