package main

// Group G5 of the "Messages a Person Reads" rewrite, round 2 (the rest of
// the intent verbs: agent, app, question, design and decision records, goal
// sync, settings coordinator, system adopt and completion, and the browser
// interface's refusals). The traced reading enforces every file of the
// group; the direct scan enforces the one it did not yet.
var _ = enforceMessages("cmd/metasystem/intent_adopt.go")

var _ = enforceTracedMessages(
	"cmd/metasystem/adapter_runtime_verbs.go",
	"cmd/metasystem/app.go",
	"cmd/metasystem/brain_boot.go",
	"cmd/metasystem/channel_verbs.go",
	"cmd/metasystem/completion.go",
	"cmd/metasystem/intent_agent.go",
	"cmd/metasystem/intent_app.go",
	"cmd/metasystem/intent_exception.go",
	"cmd/metasystem/intent_operations.go",
	"cmd/metasystem/intent_questions.go",
	"cmd/metasystem/launch_verbs.go",
	"cmd/metasystem/run.go",
	"cmd/metasystem/seat_launch.go",
	"cmd/metasystem/ui.go",
	"cmd/metasystem/ui_tools.go",
	"internal/acp/decide.go",
	"internal/acp/turn.go",
	"internal/adopt/adopt.go",
	"internal/applaunch/supervise.go",
	"internal/brain/brain.go",
	"internal/capability/select.go",
	"internal/channel/slack/slack.go",
	"internal/channel/telegram/telegram.go",
	"internal/contract/contract.go",
	"internal/contract/helpers.go",
	"internal/contract/measure.go",
	"internal/counselor/sources.go",
	"internal/covenant/covenant.go",
	"internal/launch/admit.go",
	"internal/launch/launch.go",
	"internal/launch/pack.go",
	"internal/launch/unit_run.go",
	"internal/mission/anchor.go",
	"internal/mission/ledger.go",
	"internal/mission/prompt.go",
	"internal/registry/framing.go",
	"internal/run/run.go",
	"internal/run/stop.go",
	"internal/run/waiter.go",
	"internal/runtimes/adapterfile/adapterfile.go",
	"internal/runtimes/external/external.go",
	"internal/ui/act/act.go",
	"internal/ui/act/landgate.go",
	"internal/ui/act/owner.go",
	"internal/ui/act/recover.go",
	"internal/ui/act/review.go",
	"internal/ui/httpd/httpd.go",
	"internal/ui/httpd/review.go",
	"internal/ui/lifecycle/roots.go",
	"internal/ui/lifecycle/serve.go",
	"internal/ui/partner/host.go",
	"internal/ui/partner/proposals.go",
	"internal/ui/partner/review.go",
	"internal/ui/partner/service.go",
	"internal/ui/project/edit.go",
	"internal/ui/project/review.go",
	"internal/ui/project/write.go",
	"internal/ui/review/evidence.go",
	"internal/ui/review/review.go",
	"internal/ui/session/session.go",
	"internal/ui/stickies/stickies.go",
	"internal/ui/uitools/mcp.go",
)
