package main

// Group G1a of the round-2 rewrite (status, helm, system, session, mission,
// ui, work status, question, design check, and the hook texts): every
// traced path of the group reads as the two-line rule, so the traced
// reading enforces them.
//
// Left in report mode, on purpose:
//   - internal/adapter/selftestrun.go: its traced texts are the self-test's
//     brief to the agent under test (a prompt whose PERMITTED_READ token is
//     the protocol the test checks), not a message a person reads.
//   - internal/hooks/setup_legacy.go: the tails earlier settings files
//     carried, matched byte for byte and never printed.
var _ = enforceTracedMessages(
	"cmd/metasystem/helm_return.go",
	"cmd/metasystem/helpers.go",
	"cmd/metasystem/hook_entry.go",
	"cmd/metasystem/intent.go",
	"cmd/metasystem/intent_grant_everything.go",
	"cmd/metasystem/intent_helm.go",
	"cmd/metasystem/intent_process.go",
	"cmd/metasystem/intent_table.go",
	"cmd/metasystem/main.go",
	"cmd/metasystem/process_verbs.go",
	"cmd/metasystem/wait_register.go",
	"internal/adapter/snapshot.go",
	"internal/adapter/supervisor/claude.go",
	"internal/adapter/supervisor/codex.go",
	"internal/adapter/supervisor/devin.go",
	"internal/adapter/supervisor/external.go",
	"internal/adapter/supervisor/lifecycle.go",
	"internal/authority/authority.go",
	"internal/board/board.go",
	"internal/board/card.go",
	"internal/board/mailbox.go",
	"internal/hooks/peer_delivery.go",
	"internal/hooks/runtime_hook_start.go",
	"internal/hooks/runtime_hook_stop.go",
	"internal/hooks/setup.go",
	"internal/humanauthority/authority.go",
	"internal/lock/lock.go",
	"internal/protocol/protocol.go",
	"internal/refusal/coded.go",
	"internal/report/frontier.go",
	"internal/report/stopblock.go",
	"internal/report/stopcompletion.go",
	"internal/report/stoppresentation.go",
	"internal/seat/git.go",
	"internal/seat/launch/lock.go",
	"internal/seat/launch/preflight.go",
	"internal/seat/launch/presence.go",
	"internal/seat/launch/record.go",
	"internal/seat/launch/refusal.go",
	"internal/seat/launch/secondsession.go",
	"internal/seat/launch/sequence.go",
	"internal/seat/rung.go",
	"internal/stopfence/fence.go",
	"internal/stopreport/response.go",
	"internal/stoptransition/transition.go",
	"internal/up/up.go",
)

// The direct scan: the group's files hold no violation either.
var _ = enforceMessages(
	"cmd/metasystem/helm_return.go",
	"cmd/metasystem/helpers.go",
	"cmd/metasystem/hook_entry.go",
	"cmd/metasystem/intent.go",
	"cmd/metasystem/intent_grant_everything.go",
	"cmd/metasystem/intent_helm.go",
	"cmd/metasystem/intent_process.go",
	"cmd/metasystem/intent_table.go",
	"cmd/metasystem/main.go",
	"cmd/metasystem/process_verbs.go",
	"cmd/metasystem/wait_register.go",
	"internal/adapter/selftestrun.go",
	"internal/adapter/snapshot.go",
	"internal/adapter/supervisor/claude.go",
	"internal/adapter/supervisor/codex.go",
	"internal/adapter/supervisor/devin.go",
	"internal/adapter/supervisor/external.go",
	"internal/adapter/supervisor/lifecycle.go",
	"internal/authority/authority.go",
	"internal/board/board.go",
	"internal/board/card.go",
	"internal/board/mailbox.go",
	"internal/hooks/peer_delivery.go",
	"internal/hooks/runtime_hook_start.go",
	"internal/hooks/runtime_hook_stop.go",
	"internal/hooks/setup.go",
	"internal/humanauthority/authority.go",
	"internal/lock/lock.go",
	"internal/protocol/protocol.go",
	"internal/refusal/coded.go",
	"internal/report/frontier.go",
	"internal/report/stopblock.go",
	"internal/report/stopcompletion.go",
	"internal/report/stoppresentation.go",
	"internal/seat/git.go",
	"internal/seat/launch/lock.go",
	"internal/seat/launch/preflight.go",
	"internal/seat/launch/presence.go",
	"internal/seat/launch/record.go",
	"internal/seat/launch/refusal.go",
	"internal/seat/launch/secondsession.go",
	"internal/seat/launch/sequence.go",
	"internal/seat/rung.go",
	"internal/stopfence/fence.go",
	"internal/stopreport/response.go",
	"internal/stoptransition/transition.go",
	"internal/up/up.go",
)
